import type { Language } from "@/i18n/translations"

export const logicGameCopy = {
  en: {
    reset: "Reset",
    resetGates: "Reset gates",
    chooseGate: "Choose a gate",
    level: "Level",
    sandbox: "Sandbox",
    levelsAria: "Levels",
    goal: "Goal",
    booleanConcept: "Boolean concept",
    progress: "Progress",
    progressCount: "{completed} of {total} circuits completed",
    circuitComplete: "Circuit complete!",
    badgeEarned: "Badge earned: {badge}",
    rowsMatched: "Rows matched",
    attempts: "Attempts",
    hintsUsed: "Hints used",
    whatLearned: "What you learned:",
    nextLevel: "Next level",
    needHint: "Need a Hint?",
    showHint: "Show a hint",
    showNextHint: "Show next hint",
    hintLabel: "Hint {number}:",
    feedbackNoGate: "Pick a gate to test your circuit.",
    feedbackPartial: "{matchCount} of {total} rows match. Check the rows marked Try again.",
    feedbackWrong: "Not quite. Compare the rows where your output differs from the target.",
    feedbackSolved: "All rows match. Your circuit works!",
    truthTable: "Truth table",
    targetColumn: "What should happen?",
    circuitColumn: "What your circuit does",
    result: "Result",
    correct: "Correct",
    tryAgain: "Try again",
    yes: "Yes",
    no: "No",
    notSure: "Not sure",
    output: "Output {number}",
    pickGateRow: "Pick a gate to see what happens when {inputs}.",
    correctRow: "Correct. When {inputs}, your {gate} gate makes {got}, matching {output}.",
    wrongRow: "When {inputs}, your {gate} gate makes {got}, but the goal is: {expected}.",
    inputJoiner: " and ",
    inputState: "{label} is {value}",
    on: "On",
    off: "Off",
    tutorialTitle: "How Logic Gates Work",
    tutorialP1: "Boolean logic is how computers make yes/no decisions. Every signal in a circuit is either ON or OFF, and each signal can also mean TRUE or FALSE.",
    tutorialOnTrue: "ON means TRUE",
    tutorialOffFalse: "OFF means FALSE",
    tutorialP2: "A circuit has inputs, which are switches you control, and an output, which is a light that reacts. A logic gate is a small rule that looks at the inputs and decides what the output should be.",
    tutorialP3: "Try the switches below. Toggle them and watch how each gate decides the light's output.",
    tutorialTip: "Try to predict the answer first. Then test your circuit.",
    startLevel1: "Start Level 1",
    toggleSwitchAria: "Toggle switch {label}, currently {state}",
    lightAria: "Light is {state}",
    switchLabel: "Switch {label}",
    sandboxTitle: "Sandbox: design your own truth table",
    sandboxDesc: "Tap the target outputs below to design your own rule for inputs A, B, and C. Then choose gates to build a circuit that matches it.",
    sandboxRowAria: "Row {number} target output, currently {state}",
    sandboxLevelTitle: "Level 10: Design Your Own",
    sandboxConcept: "Any decision can be built from gates.",
    sandboxMissionTitle: "Boolean Creator Challenge",
    sandboxMissionStory: "Design your own target table, then build a circuit that matches it.",
    sandboxPlainGoal: "Choose what each row of the output should be, then wire up gates to match your own design.",
    sandboxBehavior: "You decide the rule. The circuit must match whatever target you set.",
    sandboxOutputLabel: "Y (your output)",
    sandboxInputA: "First switch?",
    sandboxInputB: "Second switch?",
    sandboxInputC: "Third switch?",
    sandboxOutputQuestion: "Custom output?",
    sandboxOutputOn: "Output turns on",
    sandboxOutputOff: "Output stays off",
    sandboxHelper: "Design every switch combination, then see whether your circuit follows your custom rule.",
    sandboxSuccess: "You designed a Boolean rule from scratch and built the circuit to match it.",
    sandboxConnection: "Engineers do this exact thing: start from a desired behavior and build the logic to produce it.",
    sandboxBadgeName: "Boolean Creator",
    sandboxBadgeDescription: "Designed a circuit from scratch.",
    gateInfo: {
      AND: "Output turns On only when A and B are both On.",
      OR: "Output turns On when A or B, or both, are On.",
      NOT: "Output is the opposite of the input.",
      XOR: "Output turns On when exactly one input is On.",
      NAND: "Opposite of AND. Output turns Off only when both inputs are On.",
      NOR: "Opposite of OR. Output turns On only when both inputs are Off.",
    },
  },
  es: {
    reset: "Reiniciar",
    resetGates: "Reiniciar puertas",
    chooseGate: "Elige una puerta",
    level: "Nivel",
    sandbox: "Sandbox",
    levelsAria: "Niveles",
    goal: "Meta",
    booleanConcept: "Concepto booleano",
    progress: "Progreso",
    progressCount: "{completed} de {total} circuitos completados",
    circuitComplete: "Circuito completado!",
    badgeEarned: "Insignia ganada: {badge}",
    rowsMatched: "Filas correctas",
    attempts: "Intentos",
    hintsUsed: "Pistas usadas",
    whatLearned: "Lo que aprendiste:",
    nextLevel: "Siguiente nivel",
    needHint: "Necesitas una pista?",
    showHint: "Mostrar una pista",
    showNextHint: "Mostrar otra pista",
    hintLabel: "Pista {number}:",
    feedbackNoGate: "Elige una puerta para probar tu circuito.",
    feedbackPartial: "{matchCount} de {total} filas coinciden. Revisa las filas marcadas Intenta de nuevo.",
    feedbackWrong: "Todavia no. Compara las filas donde tu salida es distinta a la meta.",
    feedbackSolved: "Todas las filas coinciden. Tu circuito funciona!",
    truthTable: "Tabla de verdad",
    targetColumn: "Que deberia pasar?",
    circuitColumn: "Que hace tu circuito",
    result: "Resultado",
    correct: "Correcto",
    tryAgain: "Intenta de nuevo",
    yes: "Si",
    no: "No",
    notSure: "No se sabe",
    output: "Salida {number}",
    pickGateRow: "Elige una puerta para ver que pasa cuando {inputs}.",
    correctRow: "Correcto. Cuando {inputs}, tu puerta {gate} produce {got}, igual que {output}.",
    wrongRow: "Cuando {inputs}, tu puerta {gate} produce {got}, pero la meta es: {expected}.",
    inputJoiner: " y ",
    inputState: "{label} es {value}",
    on: "Encendido",
    off: "Apagado",
    tutorialTitle: "Como funcionan las puertas logicas",
    tutorialP1: "La logica booleana es la forma en que las computadoras toman decisiones de si/no. Cada senal de un circuito esta encendida o apagada, y tambien puede significar verdadero o falso.",
    tutorialOnTrue: "ENCENDIDO significa VERDADERO",
    tutorialOffFalse: "APAGADO significa FALSO",
    tutorialP2: "Un circuito tiene entradas, que son interruptores que controlas, y una salida, que es una luz que reacciona. Una puerta logica es una pequena regla que mira las entradas y decide cual debe ser la salida.",
    tutorialP3: "Prueba los interruptores de abajo. Cambialos y observa como cada puerta decide la salida de la luz.",
    tutorialTip: "Primero intenta predecir la respuesta. Luego prueba tu circuito.",
    startLevel1: "Empezar Nivel 1",
    toggleSwitchAria: "Cambiar interruptor {label}, actualmente {state}",
    lightAria: "La luz esta {state}",
    switchLabel: "Interruptor {label}",
    sandboxTitle: "Sandbox: disena tu propia tabla de verdad",
    sandboxDesc: "Toca las salidas objetivo para disenar tu propia regla para las entradas A, B y C. Luego elige puertas para construir un circuito que coincida.",
    sandboxRowAria: "Salida objetivo de la fila {number}, actualmente {state}",
    sandboxLevelTitle: "Nivel 10: Disena el tuyo",
    sandboxConcept: "Cualquier decision puede construirse con puertas.",
    sandboxMissionTitle: "Reto de creador booleano",
    sandboxMissionStory: "Disena tu propia tabla objetivo y luego construye un circuito que coincida.",
    sandboxPlainGoal: "Elige que salida debe tener cada fila y conecta puertas para igualar tu propio diseno.",
    sandboxBehavior: "Tu decides la regla. El circuito debe coincidir con el objetivo que fijes.",
    sandboxOutputLabel: "Y (tu salida)",
    sandboxInputA: "Primer interruptor?",
    sandboxInputB: "Segundo interruptor?",
    sandboxInputC: "Tercer interruptor?",
    sandboxOutputQuestion: "Salida personalizada?",
    sandboxOutputOn: "La salida se enciende",
    sandboxOutputOff: "La salida queda apagada",
    sandboxHelper: "Disena cada combinacion de interruptores y revisa si tu circuito sigue tu regla.",
    sandboxSuccess: "Disenaste una regla booleana desde cero y construiste el circuito para igualarla.",
    sandboxConnection: "Los ingenieros hacen exactamente esto: parten de un comportamiento deseado y construyen la logica para producirlo.",
    sandboxBadgeName: "Creador booleano",
    sandboxBadgeDescription: "Diseno un circuito desde cero.",
    gateInfo: {
      AND: "La salida se enciende solo cuando A y B estan encendidos.",
      OR: "La salida se enciende cuando A, B o ambos estan encendidos.",
      NOT: "La salida es lo contrario de la entrada.",
      XOR: "La salida se enciende cuando exactamente una entrada esta encendida.",
      NAND: "Lo opuesto de AND. La salida se apaga solo cuando ambas entradas estan encendidas.",
      NOR: "Lo opuesto de OR. La salida se enciende solo cuando ambas entradas estan apagadas.",
    },
  },
  zh: {
    reset: "重置",
    resetGates: "重置逻辑门",
    chooseGate: "选择一个逻辑门",
    level: "关卡",
    sandbox: "沙盒",
    levelsAria: "关卡",
    goal: "目标",
    booleanConcept: "布尔概念",
    progress: "进度",
    progressCount: "已完成 {completed}/{total} 个电路",
    circuitComplete: "电路完成！",
    badgeEarned: "获得徽章：{badge}",
    rowsMatched: "匹配行数",
    attempts: "尝试次数",
    hintsUsed: "使用提示",
    whatLearned: "你学到的：",
    nextLevel: "下一关",
    needHint: "需要提示？",
    showHint: "显示提示",
    showNextHint: "显示下一个提示",
    hintLabel: "提示 {number}：",
    feedbackNoGate: "选择一个逻辑门来测试你的电路。",
    feedbackPartial: "{matchCount}/{total} 行匹配。检查标为“再试试”的行。",
    feedbackWrong: "还不对。比较一下你的输出和目标不同的行。",
    feedbackSolved: "所有行都匹配。你的电路成功了！",
    truthTable: "真值表",
    targetColumn: "应该发生什么？",
    circuitColumn: "你的电路会做什么",
    result: "结果",
    correct: "正确",
    tryAgain: "再试试",
    yes: "是",
    no: "否",
    notSure: "不确定",
    output: "输出 {number}",
    pickGateRow: "选择一个逻辑门，看看当 {inputs} 时会发生什么。",
    correctRow: "正确。当 {inputs} 时，你的 {gate} 门产生 {got}，与 {output} 匹配。",
    wrongRow: "当 {inputs} 时，你的 {gate} 门产生 {got}，但目标是：{expected}。",
    inputJoiner: "，且",
    inputState: "{label}为{value}",
    on: "开启",
    off: "关闭",
    tutorialTitle: "逻辑门如何工作",
    tutorialP1: "布尔逻辑是计算机做“是/否”决策的方式。电路里的每个信号要么开启，要么关闭，也可以表示真或假。",
    tutorialOnTrue: "开启表示真",
    tutorialOffFalse: "关闭表示假",
    tutorialP2: "电路有输入，也就是你控制的开关；还有输出，也就是会反应的灯。逻辑门是一条小规则，会观察输入并决定输出应该是什么。",
    tutorialP3: "试试下面的开关。切换它们，观察每个逻辑门如何决定灯的输出。",
    tutorialTip: "先试着预测答案，再测试你的电路。",
    startLevel1: "开始第 1 关",
    toggleSwitchAria: "切换开关 {label}，当前为{state}",
    lightAria: "灯当前为{state}",
    switchLabel: "开关 {label}",
    sandboxTitle: "沙盒：设计你自己的真值表",
    sandboxDesc: "点击下面的目标输出，为输入 A、B、C 设计自己的规则。然后选择逻辑门，搭出匹配它的电路。",
    sandboxRowAria: "第 {number} 行目标输出，当前为{state}",
    sandboxLevelTitle: "第 10 关：自己设计",
    sandboxConcept: "任何决策都可以用逻辑门搭出来。",
    sandboxMissionTitle: "布尔创造者挑战",
    sandboxMissionStory: "设计你自己的目标表，然后搭建一个匹配它的电路。",
    sandboxPlainGoal: "选择每一行输出应该是什么，再连接逻辑门来匹配你的设计。",
    sandboxBehavior: "规则由你决定。电路必须匹配你设定的目标。",
    sandboxOutputLabel: "Y（你的输出）",
    sandboxInputA: "第一个开关？",
    sandboxInputB: "第二个开关？",
    sandboxInputC: "第三个开关？",
    sandboxOutputQuestion: "自定义输出？",
    sandboxOutputOn: "输出开启",
    sandboxOutputOff: "输出保持关闭",
    sandboxHelper: "设计每一种开关组合，再看看你的电路是否遵守自定义规则。",
    sandboxSuccess: "你从零设计了一条布尔规则，并搭出了匹配它的电路。",
    sandboxConnection: "工程师也会这样做：先确定想要的行为，再搭建能产生这个行为的逻辑。",
    sandboxBadgeName: "布尔创造者",
    sandboxBadgeDescription: "从零设计了一个电路。",
    gateInfo: {
      AND: "只有 A 和 B 都开启时，输出才会开启。",
      OR: "A 或 B，或两者都开启时，输出会开启。",
      NOT: "输出是输入的相反。",
      XOR: "正好一个输入开启时，输出会开启。",
      NAND: "AND 的相反。只有两个输入都开启时，输出才会关闭。",
      NOR: "OR 的相反。只有两个输入都关闭时，输出才会开启。",
    },
  },
} as const

export type LogicGameCopy = (typeof logicGameCopy)[Language]

export function formatLogicText(text: string, values: Record<string, string | number>) {
  return text.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? `{${key}}`))
}
