import { BADGES_BY_LEVEL } from "./badges"
import type { Language } from "@/i18n/translations"
import type { Level, TruthRow } from "./types"

function rows2(cb: (a: number, b: number) => number[]): TruthRow[] {
  const out: TruthRow[] = []
  for (const a of [0, 1]) for (const b of [0, 1]) out.push({ inputs: [a, b], outputs: cb(a, b) })
  return out
}

function rows1(cb: (a: number) => number[]): TruthRow[] {
  return [0, 1].map((a) => ({ inputs: [a], outputs: cb(a) }))
}

function rows3(cb: (a: number, b: number, c: number) => number[]): TruthRow[] {
  const out: TruthRow[] = []
  for (const a of [0, 1]) for (const b of [0, 1]) for (const c of [0, 1]) out.push({ inputs: [a, b, c], outputs: cb(a, b, c) })
  return out
}

export const LEVELS: Level[] = [
  {
    id: 1,
    title: "Level 1: AND Gate",
    concept: "Both conditions must be true.",
    missionTitle: "Robot Door Challenge",
    missionStory: "The door opens only if the robot sees a badge AND hears the password.",
    plainGoal: "Make the output turn ON only when both A and B are ON.",
    behaviorDescription: "Output turns ON only when both inputs are ON.",
    inputs: ["A", "B"],
    gates: [{ id: "g1", inputs: ["A", "B"], arity: 2, options: ["AND", "OR", "XOR", "NAND", "NOR"] }],
    outputs: [{ name: "Y", label: "Y (door)", source: { gate: "g1" } }],
    truthTable: {
      inputNames: { A: "Badge seen?", B: "Password heard?" },
      outputs: [{ name: "Y", label: "Door opens?", onText: "Door opens", offText: "Door stays closed" }],
      helperText: "Test every possible badge/password combination and see when the door should open.",
    },
    target: rows2((a, b) => [a & b]),
    hints: [
      "Look at how many times the output turns ON.",
      "The output turns on only when A and B are both ON.",
      "This is the AND gate.",
    ],
    successExplanation:
      "You learned that AND is used when two conditions must both be true, like needing a username and password.",
    realWorldConnection: "Logins, door locks, and safety checks all use AND when two things must both be true.",
    badge: BADGES_BY_LEVEL[1],
  },
  {
    id: 2,
    title: "Level 2: OR Gate",
    concept: "One true condition is enough.",
    missionTitle: "Safety Alarm Challenge",
    missionStory: "The warning light turns on if smoke OR heat is detected.",
    plainGoal: "Make the output turn ON when at least one input is ON.",
    behaviorDescription: "Output turns ON when at least one input is ON.",
    inputs: ["A", "B"],
    gates: [{ id: "g1", inputs: ["A", "B"], arity: 2, options: ["AND", "OR", "XOR", "NAND", "NOR"] }],
    outputs: [{ name: "Y", label: "Y (alarm)", source: { gate: "g1" } }],
    truthTable: {
      inputNames: { A: "Smoke detected?", B: "Heat detected?" },
      outputs: [
        { name: "Y", label: "Warning light turns on?", onText: "Warning light turns on", offText: "Warning light stays off" },
      ],
      helperText: "Test every possible smoke/heat combination and see when the warning light should turn on.",
    },
    target: rows2((a, b) => [a | b]),
    hints: [
      "Look at how many rows have an ON output.",
      "The output turns on when A is on, B is on, or both are on.",
      "This is the OR gate.",
    ],
    successExplanation:
      "You learned that OR is used when one of several conditions can trigger something, like a smoke alarm or heat sensor.",
    realWorldConnection: "Smoke detectors, alarms, and notifications often use OR — any one trigger is enough.",
    badge: BADGES_BY_LEVEL[2],
  },
  {
    id: 3,
    title: "Level 3: NOT Gate",
    concept: "NOT flips the signal.",
    missionTitle: "Night Light Challenge",
    missionStory: "The light turns on when it is NOT bright outside.",
    plainGoal: "Make the output the opposite of the input.",
    behaviorDescription: "Output flips the input. ON becomes OFF, and OFF becomes ON.",
    inputs: ["A"],
    gates: [{ id: "g1", inputs: ["A"], arity: 1, options: ["NOT", "AND", "OR"] }],
    outputs: [{ name: "Y", label: "Y (light)", source: { gate: "g1" } }],
    truthTable: {
      inputNames: { A: "Bright outside?" },
      outputs: [{ name: "Y", label: "Night light turns on?", onText: "Night light turns on", offText: "Night light stays off" }],
      helperText: "Test both outside-light conditions and see when the night light should turn on.",
    },
    target: rows1((a) => [a ? 0 : 1]),
    hints: [
      "Compare the input to the output in each row — are they ever the same?",
      "When A is ON, the output is OFF, and when A is OFF, the output is ON.",
      "This is the NOT gate.",
    ],
    successExplanation:
      "You learned that NOT flips a signal. This is useful when a system should react to something being false.",
    realWorldConnection: "Night lights, \"away mode\" sensors, and inverted switches all rely on NOT.",
    badge: BADGES_BY_LEVEL[3],
  },
  {
    id: 4,
    title: "Level 4: XOR Gate",
    concept: "True only when inputs differ.",
    missionTitle: "Choice Machine Challenge",
    missionStory: "The machine turns on when exactly one button is pressed.",
    plainGoal: "Make the output turn ON only when A and B are different.",
    behaviorDescription: "Output turns ON when exactly one input is ON.",
    inputs: ["A", "B"],
    gates: [{ id: "g1", inputs: ["A", "B"], arity: 2, options: ["AND", "OR", "XOR", "NAND", "NOR"] }],
    outputs: [{ name: "Y", label: "Y (machine)", source: { gate: "g1" } }],
    truthTable: {
      inputNames: { A: "Left button pressed?", B: "Right button pressed?" },
      outputs: [{ name: "Y", label: "Machine turns on?", onText: "Machine turns on", offText: "Machine stays off" }],
      helperText: "Test every button combination and see when exactly one button should turn the machine on.",
    },
    target: rows2((a, b) => [a ^ b]),
    hints: [
      "Look for rows where the inputs are different.",
      "The output turns ON when exactly one input is ON.",
      "This is the XOR gate.",
    ],
    successExplanation:
      "You learned that XOR is used when exactly one condition should be true. It is important in computer circuits.",
    realWorldConnection: "XOR shows up in toggle switches and in how computers compare bits without carrying.",
    badge: BADGES_BY_LEVEL[4],
  },
  {
    id: 5,
    title: "Level 5: NAND Gate",
    concept: "The opposite of AND.",
    missionTitle: "Safety Override Challenge",
    missionStory: "The system stays on unless two dangerous conditions happen together.",
    plainGoal: "Make the output turn OFF only when both A and B are ON.",
    behaviorDescription: "Output is the opposite of AND.",
    inputs: ["A", "B"],
    gates: [{ id: "g1", inputs: ["A", "B"], arity: 2, options: ["AND", "OR", "XOR", "NAND", "NOR"] }],
    outputs: [{ name: "Y", label: "Y (system on)", source: { gate: "g1" } }],
    truthTable: {
      inputNames: { A: "Overheating?", B: "Pressure unsafe?" },
      outputs: [{ name: "Y", label: "System stays on?", onText: "System stays on", offText: "System shuts off" }],
      helperText: "Test every dangerous-condition combination and see when the safety system should stay on.",
    },
    target: rows2((a, b) => [a & b ? 0 : 1]),
    hints: [
      "Find the one row where the output is different from the rest.",
      "The output turns off only when both inputs are ON — every other case is ON.",
      "This is the NAND gate.",
    ],
    successExplanation:
      "You learned that NAND is the opposite of AND. It keeps things running unless every dangerous condition is true at once.",
    realWorldConnection: "Safety overrides use NAND so a system only shuts off when every risky condition lines up.",
    badge: BADGES_BY_LEVEL[5],
  },
  {
    id: 6,
    title: "Level 6: NOR Gate",
    concept: "The opposite of OR.",
    missionTitle: "Quiet Room Challenge",
    missionStory: "The signal turns on only when no sensors are active.",
    plainGoal: "Make the output turn ON only when both A and B are OFF.",
    behaviorDescription: "Output is the opposite of OR.",
    inputs: ["A", "B"],
    gates: [{ id: "g1", inputs: ["A", "B"], arity: 2, options: ["AND", "OR", "XOR", "NAND", "NOR"] }],
    outputs: [{ name: "Y", label: "Y (quiet)", source: { gate: "g1" } }],
    truthTable: {
      inputNames: { A: "Sound sensor active?", B: "Motion sensor active?" },
      outputs: [{ name: "Y", label: "Quiet signal turns on?", onText: "Quiet signal turns on", offText: "Quiet signal stays off" }],
      helperText: "Test every sensor combination and see when the quiet-room signal should turn on.",
    },
    target: rows2((a, b) => [a | b ? 0 : 1]),
    hints: [
      "Find the one row where the output is different from the rest.",
      "The output turns on only when both inputs are OFF — every other case is OFF.",
      "This is the NOR gate.",
    ],
    successExplanation:
      "You learned that NOR is the opposite of OR. It only switches on when every condition is false.",
    realWorldConnection: "A \"do not disturb\" indicator can use NOR — quiet only when nothing at all is active.",
    badge: BADGES_BY_LEVEL[6],
  },
  {
    id: 7,
    title: "Level 7: Combine Two Gates",
    concept: "Chaining gates builds bigger decisions.",
    missionTitle: "Smart Sensor Challenge",
    missionStory:
      "Build logic from more than one decision: the sensor should fire if motion is detected AND the room is dark, or if the manual override is pressed.",
    plainGoal: "Chain two gates so the circuit fires when motion and darkness happen together, or when the manual override is on.",
    behaviorDescription: "Output turns ON when motion is detected and the room is dark, or when the manual override is on.",
    inputs: ["A", "B", "C"],
    gates: [
      { id: "g1", inputs: ["A", "B"], arity: 2, options: ["AND", "OR"] },
      { id: "g2", inputs: [{ gate: "g1" }, "C"], arity: 2, options: ["AND", "OR", "XOR", "NAND", "NOR"] },
    ],
    outputs: [{ name: "Y", label: "Y (sensor)", source: { gate: "g2" } }],
    truthTable: {
      inputNames: { A: "Motion detected?", B: "Room is dark?", C: "Manual override pressed?" },
      outputs: [{ name: "Y", label: "Sensor fires?", onText: "Sensor fires", offText: "Sensor stays quiet" }],
      helperText: "Test every motion/darkness/override combination and see when the sensor should fire.",
    },
    target: rows3((a, b, c) => [(a & b) | c]),
    hints: [
      "First decide what gate makes g1 true only when A and B are both on.",
      "Then decide what gate combines g1's result with C so either one being true is enough.",
      "g1 should be AND, and g2 should be OR.",
    ],
    successExplanation: "You learned that gates can be chained — one gate's output becomes another gate's input.",
    realWorldConnection: "Smart sensors often combine several rules this way: a motion sensor AND darkness, OR a manual override.",
    badge: BADGES_BY_LEVEL[7],
  },
  {
    id: 8,
    title: "Level 8: Half-Adder",
    concept: "Computers add numbers using logic gates.",
    missionTitle: "Tiny Computer Challenge",
    missionStory: "Build a circuit that adds two one-bit numbers.",
    plainGoal: "Add two one-bit numbers using gates: find the Sum and the Carry.",
    behaviorDescription:
      "Add two one-bit numbers. Sum shows the answer bit. Carry shows when a value moves to the next place.",
    inputs: ["A", "B"],
    gates: [
      { id: "g1", inputs: ["A", "B"], arity: 2, options: ["XOR", "OR", "AND"] },
      { id: "g2", inputs: ["A", "B"], arity: 2, options: ["AND", "OR", "XOR"] },
    ],
    outputs: [
      { name: "S", label: "Sum", source: { gate: "g1" } },
      { name: "C", label: "Carry", source: { gate: "g2" } },
    ],
    truthTable: {
      inputNames: { A: "First bit", B: "Second bit" },
      inputOnText: "1",
      inputOffText: "0",
      outputs: [
        { name: "S", label: "Sum bit", onText: "Sum bit is 1", offText: "Sum bit is 0" },
        { name: "C", label: "Carry bit", onText: "Carry bit is 1", offText: "Carry bit is 0" },
      ],
      helperText: "Test every pair of one-bit numbers and compare the sum bit and carry bit.",
    },
    target: rows2((a, b) => [a ^ b, a & b]),
    hints: [
      "Look at the Sum column first — when are A and B different?",
      "Sum needs the gate that's true when exactly one input is on. Carry needs the gate that's true only when both are on.",
      "Sum = XOR(A, B). Carry = AND(A, B).",
    ],
    successExplanation: "You built a tiny version of how computers add numbers. XOR finds the Sum, and AND finds the Carry.",
    realWorldConnection: "Every calculator and computer chip adds binary numbers using half-adders and full-adders like this one.",
    badge: BADGES_BY_LEVEL[8],
  },
  {
    id: 9,
    title: "Level 9: Security System Challenge",
    concept: "Translate a real sentence into Boolean logic.",
    missionTitle: "Security System Challenge",
    missionStory:
      "Design a school security system. The alarm should turn on if the door is open AND the teacher is NOT present.",
    plainGoal: "Build logic so the alarm turns on only when the door is open and the teacher is away.",
    behaviorDescription: "Output turns ON when A (door open) is ON and B (teacher present) is OFF.",
    inputs: ["A", "B"],
    gates: [
      { id: "g1", inputs: ["B"], arity: 1, options: ["NOT"] },
      { id: "g2", inputs: ["A", { gate: "g1" }], arity: 2, options: ["AND", "OR", "NAND", "NOR"] },
    ],
    outputs: [{ name: "Y", label: "Y (alarm)", source: { gate: "g2" } }],
    truthTable: {
      inputNames: { A: "Door open?", B: "Teacher present?" },
      outputs: [{ name: "Y", label: "Alarm turns on?", onText: "Alarm turns on", offText: "Alarm stays off" }],
      helperText: "Test every door/teacher combination and see when the school alarm should turn on.",
    },
    target: rows2((a, b) => [a & (b ? 0 : 1)]),
    hints: [
      "First flip \"teacher present\" so it reads \"teacher NOT present.\"",
      "Then combine \"door open\" with \"teacher NOT present\" so both must be true.",
      "g1 should be NOT(B), and g2 should be AND(A, g1).",
    ],
    successExplanation: "You translated a real sentence into Boolean logic — the same skill used to write real security software.",
    realWorldConnection: "Real security systems, smart locks, and alarms are built by turning sentences like this into AND/OR/NOT logic.",
    badge: BADGES_BY_LEVEL[9],
  },
]

type LevelText = Omit<Level, "id" | "inputs" | "gates" | "outputs" | "target" | "badge"> & {
  outputs: Level["outputs"]
  badge: Level["badge"]
}

const LOCALIZED_LEVEL_TEXT: Record<Exclude<Language, "en">, Record<number, LevelText>> = {
  es: {
    1: {
      title: "Nivel 1: Puerta AND",
      concept: "Las dos condiciones deben ser verdaderas.",
      missionTitle: "Reto de la puerta del robot",
      missionStory: "La puerta solo se abre si el robot ve una credencial AND escucha la contraseña.",
      plainGoal: "Haz que la salida se encienda solo cuando A y B esten encendidos.",
      behaviorDescription: "La salida se enciende solo cuando ambas entradas estan encendidas.",
      outputs: [{ name: "Y", label: "Y (puerta)", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "Vio la credencial?", B: "Escucho la contraseña?" },
        outputs: [{ name: "Y", label: "La puerta se abre?", onText: "La puerta se abre", offText: "La puerta queda cerrada" }],
        helperText: "Prueba cada combinacion de credencial y contraseña para ver cuando debe abrirse la puerta.",
      },
      hints: ["Mira cuantas veces se enciende la salida.", "La salida se enciende solo cuando A y B estan encendidos.", "Esta es la puerta AND."],
      successExplanation: "Aprendiste que AND se usa cuando dos condiciones deben cumplirse al mismo tiempo, como tener usuario y contraseña.",
      realWorldConnection: "Los inicios de sesion, cerraduras y revisiones de seguridad usan AND cuando dos cosas deben ser verdaderas.",
      badge: { id: "and-master", name: "Maestria AND", description: "Las dos condiciones deben ser verdaderas." },
    },
    2: {
      title: "Nivel 2: Puerta OR",
      concept: "Una condicion verdadera es suficiente.",
      missionTitle: "Reto de alarma de seguridad",
      missionStory: "La luz de advertencia se enciende si se detecta humo OR calor.",
      plainGoal: "Haz que la salida se encienda cuando al menos una entrada este encendida.",
      behaviorDescription: "La salida se enciende cuando al menos una entrada esta encendida.",
      outputs: [{ name: "Y", label: "Y (alarma)", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "Humo detectado?", B: "Calor detectado?" },
        outputs: [{ name: "Y", label: "La luz de advertencia se enciende?", onText: "La luz se enciende", offText: "La luz queda apagada" }],
        helperText: "Prueba cada combinacion de humo y calor para ver cuando debe encenderse la advertencia.",
      },
      hints: ["Mira cuantas filas tienen la salida encendida.", "La salida se enciende cuando A esta encendido, B esta encendido o ambos lo estan.", "Esta es la puerta OR."],
      successExplanation: "Aprendiste que OR se usa cuando cualquiera de varias condiciones puede activar algo.",
      realWorldConnection: "Detectores de humo, alarmas y notificaciones suelen usar OR: basta con un solo disparador.",
      badge: { id: "or-explorer", name: "Explorador OR", description: "Una condicion verdadera es suficiente." },
    },
    3: {
      title: "Nivel 3: Puerta NOT",
      concept: "NOT invierte la señal.",
      missionTitle: "Reto de luz nocturna",
      missionStory: "La luz se enciende cuando NO hay mucha luz afuera.",
      plainGoal: "Haz que la salida sea lo contrario de la entrada.",
      behaviorDescription: "La salida invierte la entrada. Encendido se vuelve apagado, y apagado se vuelve encendido.",
      outputs: [{ name: "Y", label: "Y (luz)", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "Hay mucha luz afuera?" },
        outputs: [{ name: "Y", label: "La luz nocturna se enciende?", onText: "La luz se enciende", offText: "La luz queda apagada" }],
        helperText: "Prueba las dos condiciones de luz exterior para ver cuando debe encenderse la luz nocturna.",
      },
      hints: ["Compara la entrada con la salida en cada fila: alguna vez son iguales?", "Cuando A esta encendido, la salida esta apagada; cuando A esta apagado, la salida esta encendida.", "Esta es la puerta NOT."],
      successExplanation: "Aprendiste que NOT invierte una señal. Sirve cuando un sistema debe reaccionar a algo que no esta ocurriendo.",
      realWorldConnection: "Luces nocturnas, sensores de modo ausente e interruptores invertidos usan NOT.",
      badge: { id: "not-flipper", name: "Inversor NOT", description: "Cambia encendido por apagado y apagado por encendido." },
    },
    4: {
      title: "Nivel 4: Puerta XOR",
      concept: "Verdadero solo cuando las entradas son diferentes.",
      missionTitle: "Reto de maquina de eleccion",
      missionStory: "La maquina se enciende cuando se presiona exactamente un boton.",
      plainGoal: "Haz que la salida se encienda solo cuando A y B sean diferentes.",
      behaviorDescription: "La salida se enciende cuando exactamente una entrada esta encendida.",
      outputs: [{ name: "Y", label: "Y (maquina)", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "Boton izquierdo presionado?", B: "Boton derecho presionado?" },
        outputs: [{ name: "Y", label: "La maquina se enciende?", onText: "La maquina se enciende", offText: "La maquina queda apagada" }],
        helperText: "Prueba cada combinacion de botones para ver cuando exactamente un boton debe encender la maquina.",
      },
      hints: ["Busca las filas donde las entradas son diferentes.", "La salida se enciende cuando exactamente una entrada esta encendida.", "Esta es la puerta XOR."],
      successExplanation: "Aprendiste que XOR se usa cuando exactamente una condicion debe ser verdadera.",
      realWorldConnection: "XOR aparece en interruptores de cambio y en como las computadoras comparan bits sin llevar.",
      badge: { id: "xor-solver", name: "Solucionador XOR", description: "Verdadero solo cuando las entradas son diferentes." },
    },
    5: {
      title: "Nivel 5: Puerta NAND",
      concept: "Lo opuesto de AND.",
      missionTitle: "Reto de anulacion de seguridad",
      missionStory: "El sistema sigue encendido a menos que dos condiciones peligrosas ocurran juntas.",
      plainGoal: "Haz que la salida se apague solo cuando A y B esten encendidos.",
      behaviorDescription: "La salida es lo opuesto de AND.",
      outputs: [{ name: "Y", label: "Y (sistema encendido)", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "Sobrecalentamiento?", B: "Presion insegura?" },
        outputs: [{ name: "Y", label: "El sistema sigue encendido?", onText: "El sistema sigue encendido", offText: "El sistema se apaga" }],
        helperText: "Prueba cada combinacion de condiciones peligrosas para ver cuando debe seguir encendido el sistema.",
      },
      hints: ["Encuentra la unica fila donde la salida es diferente a las demas.", "La salida se apaga solo cuando ambas entradas estan encendidas; en cualquier otro caso esta encendida.", "Esta es la puerta NAND."],
      successExplanation: "Aprendiste que NAND es lo opuesto de AND. Mantiene las cosas funcionando a menos que todas las condiciones peligrosas sean verdaderas a la vez.",
      realWorldConnection: "Las anulaciones de seguridad usan NAND para apagar un sistema solo cuando todos los riesgos coinciden.",
      badge: { id: "gate-inverter", name: "Inversor de puertas", description: "AND invertida." },
    },
    6: {
      title: "Nivel 6: Puerta NOR",
      concept: "Lo opuesto de OR.",
      missionTitle: "Reto de cuarto silencioso",
      missionStory: "La señal se enciende solo cuando ningun sensor esta activo.",
      plainGoal: "Haz que la salida se encienda solo cuando A y B esten apagados.",
      behaviorDescription: "La salida es lo opuesto de OR.",
      outputs: [{ name: "Y", label: "Y (silencio)", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "Sensor de sonido activo?", B: "Sensor de movimiento activo?" },
        outputs: [{ name: "Y", label: "La señal de silencio se enciende?", onText: "La señal se enciende", offText: "La señal queda apagada" }],
        helperText: "Prueba cada combinacion de sensores para ver cuando debe encenderse la señal de silencio.",
      },
      hints: ["Encuentra la unica fila donde la salida es diferente a las demas.", "La salida se enciende solo cuando ambas entradas estan apagadas; en cualquier otro caso esta apagada.", "Esta es la puerta NOR."],
      successExplanation: "Aprendiste que NOR es lo opuesto de OR. Solo se enciende cuando todas las condiciones son falsas.",
      realWorldConnection: "Un indicador de no molestar puede usar NOR: hay silencio solo cuando nada esta activo.",
      badge: { id: "nor-master", name: "Maestria NOR", description: "OR invertida." },
    },
    7: {
      title: "Nivel 7: Combina dos puertas",
      concept: "Encadenar puertas construye decisiones mas grandes.",
      missionTitle: "Reto de sensor inteligente",
      missionStory: "Construye logica con mas de una decision: el sensor debe activarse si hay movimiento AND el cuarto esta oscuro, o si se presiona el control manual.",
      plainGoal: "Encadena dos puertas para que el circuito se active con movimiento y oscuridad, o cuando el control manual este encendido.",
      behaviorDescription: "La salida se enciende cuando hay movimiento y el cuarto esta oscuro, o cuando el control manual esta encendido.",
      outputs: [{ name: "Y", label: "Y (sensor)", source: { gate: "g2" } }],
      truthTable: {
        inputNames: { A: "Movimiento detectado?", B: "El cuarto esta oscuro?", C: "Control manual presionado?" },
        outputs: [{ name: "Y", label: "El sensor se activa?", onText: "El sensor se activa", offText: "El sensor queda quieto" }],
        helperText: "Prueba cada combinacion de movimiento, oscuridad y control manual para ver cuando debe activarse el sensor.",
      },
      hints: ["Primero decide que puerta hace que g1 sea verdadera solo cuando A y B estan encendidos.", "Luego decide que puerta combina el resultado de g1 con C para que cualquiera de los dos baste.", "g1 debe ser AND y g2 debe ser OR."],
      successExplanation: "Aprendiste que las puertas se pueden encadenar: la salida de una puerta se vuelve entrada de otra.",
      realWorldConnection: "Los sensores inteligentes suelen combinar reglas asi: movimiento AND oscuridad, OR un control manual.",
      badge: { id: "circuit-builder", name: "Constructor de circuitos", description: "Encadeno dos puertas." },
    },
    8: {
      title: "Nivel 8: Medio sumador",
      concept: "Las computadoras suman numeros con puertas logicas.",
      missionTitle: "Reto de mini computadora",
      missionStory: "Construye un circuito que sume dos numeros de un bit.",
      plainGoal: "Suma dos numeros de un bit usando puertas: encuentra la suma y el acarreo.",
      behaviorDescription: "Suma dos numeros de un bit. Suma muestra el bit de respuesta; acarreo muestra cuando un valor pasa al siguiente lugar.",
      outputs: [
        { name: "S", label: "Suma", source: { gate: "g1" } },
        { name: "C", label: "Acarreo", source: { gate: "g2" } },
      ],
      truthTable: {
        inputNames: { A: "Primer bit", B: "Segundo bit" },
        inputOnText: "1",
        inputOffText: "0",
        outputs: [
          { name: "S", label: "Bit de suma", onText: "La suma es 1", offText: "La suma es 0" },
          { name: "C", label: "Bit de acarreo", onText: "El acarreo es 1", offText: "El acarreo es 0" },
        ],
        helperText: "Prueba cada par de numeros de un bit y compara el bit de suma con el bit de acarreo.",
      },
      hints: ["Mira primero la columna de suma: cuando son diferentes A y B?", "La suma necesita la puerta que es verdadera cuando exactamente una entrada esta encendida. El acarreo necesita la puerta verdadera solo cuando ambas estan encendidas.", "Suma = XOR(A, B). Acarreo = AND(A, B)."],
      successExplanation: "Construiste una version pequena de como las computadoras suman numeros. XOR encuentra la suma y AND encuentra el acarreo.",
      realWorldConnection: "Toda calculadora y chip de computadora suma numeros binarios usando medios sumadores y sumadores completos como este.",
      badge: { id: "half-adder-hero", name: "Heroe del medio sumador", description: "Construyo un sumador binario pequeno." },
    },
    9: {
      title: "Nivel 9: Reto de sistema de seguridad",
      concept: "Traduce una frase real a logica booleana.",
      missionTitle: "Reto de sistema de seguridad",
      missionStory: "Disena un sistema de seguridad escolar. La alarma debe encenderse si la puerta esta abierta AND el maestro NO esta presente.",
      plainGoal: "Construye logica para que la alarma se encienda solo cuando la puerta esta abierta y el maestro no esta.",
      behaviorDescription: "La salida se enciende cuando A (puerta abierta) esta encendido y B (maestro presente) esta apagado.",
      outputs: [{ name: "Y", label: "Y (alarma)", source: { gate: "g2" } }],
      truthTable: {
        inputNames: { A: "Puerta abierta?", B: "Maestro presente?" },
        outputs: [{ name: "Y", label: "La alarma se enciende?", onText: "La alarma se enciende", offText: "La alarma queda apagada" }],
        helperText: "Prueba cada combinacion de puerta y maestro para ver cuando debe encenderse la alarma escolar.",
      },
      hints: ["Primero invierte \"maestro presente\" para leer \"maestro NO presente\".", "Luego combina \"puerta abierta\" con \"maestro NO presente\" para que ambas sean verdaderas.", "g1 debe ser NOT(B) y g2 debe ser AND(A, g1)."],
      successExplanation: "Tradujiste una frase real a logica booleana, la misma habilidad que se usa para escribir software de seguridad.",
      realWorldConnection: "Los sistemas de seguridad, cerraduras inteligentes y alarmas se construyen convirtiendo frases en logica AND/OR/NOT.",
      badge: { id: "security-system-designer", name: "Disenador de seguridad", description: "Convirtio una frase en logica booleana." },
    },
  },
  zh: {
    1: {
      title: "第 1 关：AND 门",
      concept: "两个条件都必须为真。",
      missionTitle: "机器人门禁挑战",
      missionStory: "只有当机器人看见证件 AND 听到密码时，门才会打开。",
      plainGoal: "让输出只在 A 和 B 都开启时开启。",
      behaviorDescription: "只有两个输入都开启时，输出才会开启。",
      outputs: [{ name: "Y", label: "Y（门）", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "看到证件？", B: "听到密码？" },
        outputs: [{ name: "Y", label: "门会打开吗？", onText: "门打开", offText: "门保持关闭" }],
        helperText: "测试每一种证件和密码组合，看看门什么时候应该打开。",
      },
      hints: ["看看输出开启了几次。", "只有 A 和 B 都开启时，输出才会开启。", "这就是 AND 门。"],
      successExplanation: "你学会了 AND 用在两个条件都必须成立的时候，比如同时需要用户名和密码。",
      realWorldConnection: "登录、门锁和安全检查都会在两件事必须同时为真时使用 AND。",
      badge: { id: "and-master", name: "AND 高手", description: "两个条件都必须为真。" },
    },
    2: {
      title: "第 2 关：OR 门",
      concept: "一个条件为真就够了。",
      missionTitle: "安全警报挑战",
      missionStory: "如果检测到烟雾 OR 热量，警示灯就会亮。",
      plainGoal: "让输出在至少一个输入开启时开启。",
      behaviorDescription: "至少一个输入开启时，输出就会开启。",
      outputs: [{ name: "Y", label: "Y（警报）", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "检测到烟雾？", B: "检测到热量？" },
        outputs: [{ name: "Y", label: "警示灯会亮吗？", onText: "警示灯亮起", offText: "警示灯保持关闭" }],
        helperText: "测试每一种烟雾和热量组合，看看警示灯什么时候应该亮。",
      },
      hints: ["看看有多少行输出是开启的。", "A 开启、B 开启，或两者都开启时，输出都会开启。", "这就是 OR 门。"],
      successExplanation: "你学会了 OR 用在多个条件中任意一个就能触发结果的时候。",
      realWorldConnection: "烟雾探测器、警报和通知常用 OR：任何一个触发条件都足够。",
      badge: { id: "or-explorer", name: "OR 探索者", description: "一个条件为真就够了。" },
    },
    3: {
      title: "第 3 关：NOT 门",
      concept: "NOT 会反转信号。",
      missionTitle: "夜灯挑战",
      missionStory: "当外面不是很亮时，灯会亮。",
      plainGoal: "让输出变成输入的相反值。",
      behaviorDescription: "输出会反转输入。开启变关闭，关闭变开启。",
      outputs: [{ name: "Y", label: "Y（灯）", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "外面很亮？" },
        outputs: [{ name: "Y", label: "夜灯会亮吗？", onText: "夜灯亮起", offText: "夜灯保持关闭" }],
        helperText: "测试两种外部光线情况，看看夜灯什么时候应该亮。",
      },
      hints: ["比较每一行的输入和输出，它们有没有相同的时候？", "A 开启时输出关闭；A 关闭时输出开启。", "这就是 NOT 门。"],
      successExplanation: "你学会了 NOT 会反转信号。当系统需要对某件事不成立做反应时，它很有用。",
      realWorldConnection: "夜灯、离家模式传感器和反向开关都会用到 NOT。",
      badge: { id: "not-flipper", name: "NOT 反转员", description: "把开启变关闭，把关闭变开启。" },
    },
    4: {
      title: "第 4 关：XOR 门",
      concept: "只有输入不同才为真。",
      missionTitle: "选择机器挑战",
      missionStory: "只有正好按下一个按钮时，机器才会启动。",
      plainGoal: "让输出只在 A 和 B 不同的时候开启。",
      behaviorDescription: "正好一个输入开启时，输出才会开启。",
      outputs: [{ name: "Y", label: "Y（机器）", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "左按钮按下？", B: "右按钮按下？" },
        outputs: [{ name: "Y", label: "机器会启动吗？", onText: "机器启动", offText: "机器保持关闭" }],
        helperText: "测试每一种按钮组合，看看什么时候正好一个按钮会启动机器。",
      },
      hints: ["找出输入不同的那些行。", "正好一个输入开启时，输出会开启。", "这就是 XOR 门。"],
      successExplanation: "你学会了 XOR 用在正好一个条件应该为真的情况。",
      realWorldConnection: "XOR 会出现在切换开关中，也出现在计算机比较二进制位的过程中。",
      badge: { id: "xor-solver", name: "XOR 解题者", description: "只有输入不同才为真。" },
    },
    5: {
      title: "第 5 关：NAND 门",
      concept: "AND 的相反。",
      missionTitle: "安全覆盖挑战",
      missionStory: "除非两个危险条件同时发生，否则系统保持开启。",
      plainGoal: "让输出只在 A 和 B 都开启时关闭。",
      behaviorDescription: "输出是 AND 的相反。",
      outputs: [{ name: "Y", label: "Y（系统开启）", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "过热？", B: "压力不安全？" },
        outputs: [{ name: "Y", label: "系统保持开启吗？", onText: "系统保持开启", offText: "系统关闭" }],
        helperText: "测试每一种危险条件组合，看看安全系统什么时候应该保持开启。",
      },
      hints: ["找出唯一一行和其他行不同的输出。", "只有两个输入都开启时，输出才会关闭；其他情况都会开启。", "这就是 NAND 门。"],
      successExplanation: "你学会了 NAND 是 AND 的相反。它会让系统保持运行，除非所有危险条件同时成立。",
      realWorldConnection: "安全覆盖会用 NAND，让系统只有在所有风险都出现时才关闭。",
      badge: { id: "gate-inverter", name: "逻辑门反转员", description: "反转后的 AND。" },
    },
    6: {
      title: "第 6 关：NOR 门",
      concept: "OR 的相反。",
      missionTitle: "安静房间挑战",
      missionStory: "只有当没有任何传感器处于活动状态时，信号才会开启。",
      plainGoal: "让输出只在 A 和 B 都关闭时开启。",
      behaviorDescription: "输出是 OR 的相反。",
      outputs: [{ name: "Y", label: "Y（安静）", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "声音传感器活动？", B: "运动传感器活动？" },
        outputs: [{ name: "Y", label: "安静信号会开启吗？", onText: "安静信号开启", offText: "安静信号保持关闭" }],
        helperText: "测试每一种传感器组合，看看安静房间信号什么时候应该开启。",
      },
      hints: ["找出唯一一行和其他行不同的输出。", "只有两个输入都关闭时，输出才会开启；其他情况都会关闭。", "这就是 NOR 门。"],
      successExplanation: "你学会了 NOR 是 OR 的相反。它只有在所有条件都为假时才开启。",
      realWorldConnection: "请勿打扰指示灯可以用 NOR：只有完全没有活动时才显示安静。",
      badge: { id: "nor-master", name: "NOR 高手", description: "反转后的 OR。" },
    },
    7: {
      title: "第 7 关：组合两个逻辑门",
      concept: "把逻辑门串起来，可以做出更大的决策。",
      missionTitle: "智能传感器挑战",
      missionStory: "用不止一个判断来搭逻辑：如果检测到运动 AND 房间很暗，或者手动覆盖被按下，传感器就应触发。",
      plainGoal: "串联两个逻辑门，让电路在运动和黑暗同时出现，或手动覆盖开启时触发。",
      behaviorDescription: "检测到运动并且房间很暗，或手动覆盖开启时，输出会开启。",
      outputs: [{ name: "Y", label: "Y（传感器）", source: { gate: "g2" } }],
      truthTable: {
        inputNames: { A: "检测到运动？", B: "房间很暗？", C: "按下手动覆盖？" },
        outputs: [{ name: "Y", label: "传感器会触发吗？", onText: "传感器触发", offText: "传感器保持安静" }],
        helperText: "测试每一种运动、黑暗和手动覆盖组合，看看传感器什么时候应该触发。",
      },
      hints: ["先决定什么门会让 g1 只在 A 和 B 都开启时为真。", "再决定什么门把 g1 的结果和 C 组合起来，让任意一个为真就足够。", "g1 应该是 AND，g2 应该是 OR。"],
      successExplanation: "你学会了逻辑门可以串联：一个门的输出会成为另一个门的输入。",
      realWorldConnection: "智能传感器常这样组合规则：运动 AND 黑暗，OR 手动覆盖。",
      badge: { id: "circuit-builder", name: "电路搭建者", description: "把两个逻辑门串联起来。" },
    },
    8: {
      title: "第 8 关：半加器",
      concept: "计算机用逻辑门做加法。",
      missionTitle: "小小计算机挑战",
      missionStory: "搭一个能把两个一位二进制数相加的电路。",
      plainGoal: "用逻辑门相加两个一位数：找出和与进位。",
      behaviorDescription: "相加两个一位数。和显示答案位，进位显示值是否进入下一位。",
      outputs: [
        { name: "S", label: "和", source: { gate: "g1" } },
        { name: "C", label: "进位", source: { gate: "g2" } },
      ],
      truthTable: {
        inputNames: { A: "第一位", B: "第二位" },
        inputOnText: "1",
        inputOffText: "0",
        outputs: [
          { name: "S", label: "和位", onText: "和位是 1", offText: "和位是 0" },
          { name: "C", label: "进位位", onText: "进位是 1", offText: "进位是 0" },
        ],
        helperText: "测试每一对一位二进制数，比较和位与进位位。",
      },
      hints: ["先看和这一列：A 和 B 什么时候不同？", "和需要一个正好一个输入开启时为真的门。进位需要一个只有两个输入都开启时为真的门。", "和 = XOR(A, B)。进位 = AND(A, B)。"],
      successExplanation: "你搭出了计算机做加法的一个小版本。XOR 找出和，AND 找出进位。",
      realWorldConnection: "每个计算器和电脑芯片都会用这样的半加器和全加器来相加二进制数。",
      badge: { id: "half-adder-hero", name: "半加器英雄", description: "搭出了小小的二进制加法器。" },
    },
    9: {
      title: "第 9 关：安全系统挑战",
      concept: "把真实句子翻译成布尔逻辑。",
      missionTitle: "安全系统挑战",
      missionStory: "设计一个学校安全系统。如果门开着 AND 老师不在场，警报就应该响起。",
      plainGoal: "搭出逻辑，让警报只在门开着且老师不在时开启。",
      behaviorDescription: "当 A（门开着）开启且 B（老师在场）关闭时，输出会开启。",
      outputs: [{ name: "Y", label: "Y（警报）", source: { gate: "g2" } }],
      truthTable: {
        inputNames: { A: "门开着？", B: "老师在场？" },
        outputs: [{ name: "Y", label: "警报会开启吗？", onText: "警报开启", offText: "警报保持关闭" }],
        helperText: "测试每一种门和老师的组合，看看学校警报什么时候应该开启。",
      },
      hints: ["先把“老师在场”反转成“老师不在场”。", "再把“门开着”和“老师不在场”组合起来，让两者都必须为真。", "g1 应该是 NOT(B)，g2 应该是 AND(A, g1)。"],
      successExplanation: "你把一句真实的话翻译成了布尔逻辑，这也是编写安全软件会用到的技能。",
      realWorldConnection: "真实安全系统、智能锁和警报会把句子转换成 AND/OR/NOT 逻辑来构建。",
      badge: { id: "security-system-designer", name: "安全系统设计师", description: "把一句话变成了布尔逻辑。" },
    },
  },
  pt: {
    1: {
      title: "Nível 1: Porta AND",
      concept: "As duas condições precisam ser verdadeiras.",
      missionTitle: "Desafio da porta do robô",
      missionStory: "A porta só abre se o robô vir um crachá AND ouvir a senha.",
      plainGoal: "Faça a saída ligar só quando A e B estiverem ligados.",
      behaviorDescription: "A saída liga só quando as duas entradas estão ligadas.",
      outputs: [{ name: "Y", label: "Y (porta)", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "Viu o crachá?", B: "Ouviu a senha?" },
        outputs: [{ name: "Y", label: "A porta abre?", onText: "A porta abre", offText: "A porta fica fechada" }],
        helperText: "Teste cada combinação de crachá e senha para ver quando a porta deve abrir.",
      },
      hints: ["Veja quantas vezes a saída liga.", "A saída liga só quando A e B estão ligados.", "Esta é a porta AND."],
      successExplanation: "Você aprendeu que o AND serve quando duas condições precisam acontecer ao mesmo tempo, como ter usuário e senha.",
      realWorldConnection: "Logins, fechaduras e checagens de segurança usam AND quando duas coisas precisam ser verdadeiras.",
      badge: { id: "and-master", name: "Domínio do AND", description: "As duas condições precisam ser verdadeiras." },
    },
    2: {
      title: "Nível 2: Porta OR",
      concept: "Uma condição verdadeira já basta.",
      missionTitle: "Desafio do alarme de segurança",
      missionStory: "A luz de alerta acende se houver fumaça OR calor.",
      plainGoal: "Faça a saída ligar quando pelo menos uma entrada estiver ligada.",
      behaviorDescription: "A saída liga quando pelo menos uma entrada está ligada.",
      outputs: [{ name: "Y", label: "Y (alarme)", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "Fumaça detectada?", B: "Calor detectado?" },
        outputs: [{ name: "Y", label: "A luz de alerta acende?", onText: "A luz acende", offText: "A luz fica apagada" }],
        helperText: "Teste cada combinação de fumaça e calor para ver quando o alerta deve acender.",
      },
      hints: ["Veja quantas linhas têm a saída ligada.", "A saída liga quando A está ligado, B está ligado ou os dois estão.", "Esta é a porta OR."],
      successExplanation: "Você aprendeu que o OR serve quando qualquer uma de várias condições pode disparar alguma coisa.",
      realWorldConnection: "Detectores de fumaça, alarmes e notificações costumam usar OR: basta um único gatilho.",
      badge: { id: "or-explorer", name: "Explorador do OR", description: "Uma condição verdadeira já basta." },
    },
    3: {
      title: "Nível 3: Porta NOT",
      concept: "O NOT inverte o sinal.",
      missionTitle: "Desafio da luz noturna",
      missionStory: "A luz acende quando NÃO está claro lá fora.",
      plainGoal: "Faça a saída ser o contrário da entrada.",
      behaviorDescription: "A saída inverte a entrada. Ligado vira desligado, e desligado vira ligado.",
      outputs: [{ name: "Y", label: "Y (luz)", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "Está claro lá fora?" },
        outputs: [{ name: "Y", label: "A luz noturna acende?", onText: "A luz acende", offText: "A luz fica apagada" }],
        helperText: "Teste as duas condições de claridade lá fora para ver quando a luz noturna deve acender.",
      },
      hints: ["Compare a entrada com a saída em cada linha: elas chegam a ser iguais?", "Quando A está ligado, a saída está desligada; quando A está desligado, a saída está ligada.", "Esta é a porta NOT."],
      successExplanation: "Você aprendeu que o NOT inverte um sinal. Ele serve quando um sistema precisa reagir a algo que NÃO está acontecendo.",
      realWorldConnection: "Luzes noturnas, sensores de modo ausente e interruptores invertidos usam NOT.",
      badge: { id: "not-flipper", name: "Inversor NOT", description: "Troca ligado por desligado e desligado por ligado." },
    },
    4: {
      title: "Nível 4: Porta XOR",
      concept: "Verdadeiro só quando as entradas são diferentes.",
      missionTitle: "Desafio da máquina de escolha",
      missionStory: "A máquina liga quando exatamente um botão é apertado.",
      plainGoal: "Faça a saída ligar só quando A e B forem diferentes.",
      behaviorDescription: "A saída liga quando exatamente uma entrada está ligada.",
      outputs: [{ name: "Y", label: "Y (máquina)", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "Botão esquerdo apertado?", B: "Botão direito apertado?" },
        outputs: [{ name: "Y", label: "A máquina liga?", onText: "A máquina liga", offText: "A máquina fica desligada" }],
        helperText: "Teste cada combinação de botões para ver quando exatamente um botão deve ligar a máquina.",
      },
      hints: ["Procure as linhas em que as entradas são diferentes.", "A saída liga quando exatamente uma entrada está ligada.", "Esta é a porta XOR."],
      successExplanation: "Você aprendeu que o XOR serve quando exatamente uma condição precisa ser verdadeira.",
      realWorldConnection: "O XOR aparece em interruptores paralelos (three-way) e no jeito como os computadores comparam bits sem vai-um.",
      badge: { id: "xor-solver", name: "Solucionador XOR", description: "Verdadeiro só quando as entradas são diferentes." },
    },
    5: {
      title: "Nível 5: Porta NAND",
      concept: "O contrário do AND.",
      missionTitle: "Desafio do desligamento de segurança",
      missionStory: "O sistema continua ligado, a não ser que duas condições perigosas aconteçam juntas.",
      plainGoal: "Faça a saída desligar só quando A e B estiverem ligados.",
      behaviorDescription: "A saída é o contrário do AND.",
      outputs: [{ name: "Y", label: "Y (sistema ligado)", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "Superaquecimento?", B: "Pressão perigosa?" },
        outputs: [{ name: "Y", label: "O sistema continua ligado?", onText: "O sistema continua ligado", offText: "O sistema desliga" }],
        helperText: "Teste cada combinação de condições perigosas para ver quando o sistema deve continuar ligado.",
      },
      hints: ["Encontre a única linha em que a saída é diferente das outras.", "A saída desliga só quando as duas entradas estão ligadas; em qualquer outro caso ela fica ligada.", "Esta é a porta NAND."],
      successExplanation: "Você aprendeu que o NAND é o contrário do AND. Ele mantém tudo funcionando, a não ser que todas as condições perigosas sejam verdadeiras ao mesmo tempo.",
      realWorldConnection: "Os desligamentos de segurança usam NAND para desligar um sistema só quando todos os riscos aparecem juntos.",
      badge: { id: "gate-inverter", name: "Inversor de portas", description: "AND invertido." },
    },
    6: {
      title: "Nível 6: Porta NOR",
      concept: "O contrário do OR.",
      missionTitle: "Desafio do quarto silencioso",
      missionStory: "O aviso acende só quando nenhum sensor está ativo.",
      plainGoal: "Faça a saída ligar só quando A e B estiverem desligados.",
      behaviorDescription: "A saída é o contrário do OR.",
      outputs: [{ name: "Y", label: "Y (silêncio)", source: { gate: "g1" } }],
      truthTable: {
        inputNames: { A: "Sensor de som ativo?", B: "Sensor de movimento ativo?" },
        outputs: [{ name: "Y", label: "O aviso de silêncio acende?", onText: "O aviso acende", offText: "O aviso fica apagado" }],
        helperText: "Teste cada combinação de sensores para ver quando o aviso de silêncio deve acender.",
      },
      hints: ["Encontre a única linha em que a saída é diferente das outras.", "A saída liga só quando as duas entradas estão desligadas; em qualquer outro caso ela fica desligada.", "Esta é a porta NOR."],
      successExplanation: "Você aprendeu que o NOR é o contrário do OR. Ele só liga quando todas as condições são falsas.",
      realWorldConnection: "Um indicador de não perturbe pode usar NOR: só há silêncio quando nada está ativo.",
      badge: { id: "nor-master", name: "Domínio do NOR", description: "OR invertido." },
    },
    7: {
      title: "Nível 7: Combine duas portas",
      concept: "Encadear portas constrói decisões maiores.",
      missionTitle: "Desafio do sensor inteligente",
      missionStory: "Monte uma lógica com mais de uma decisão: o sensor deve disparar se houver movimento AND o cômodo estiver escuro, ou se o controle manual for acionado.",
      plainGoal: "Encadeie duas portas para o circuito disparar com movimento e escuridão, ou quando o controle manual estiver ligado.",
      behaviorDescription: "A saída liga quando há movimento e o cômodo está escuro, ou quando o controle manual está ligado.",
      outputs: [{ name: "Y", label: "Y (sensor)", source: { gate: "g2" } }],
      truthTable: {
        inputNames: { A: "Movimento detectado?", B: "O cômodo está escuro?", C: "Controle manual acionado?" },
        outputs: [{ name: "Y", label: "O sensor dispara?", onText: "O sensor dispara", offText: "O sensor fica parado" }],
        helperText: "Teste cada combinação de movimento, escuridão e controle manual para ver quando o sensor deve disparar.",
      },
      hints: ["Primeiro decida qual porta faz g1 ser verdadeira só quando A e B estão ligados.", "Depois decida qual porta combina o resultado de g1 com C, para que qualquer um dos dois já baste.", "g1 deve ser AND e g2 deve ser OR."],
      successExplanation: "Você aprendeu que dá para encadear portas: a saída de uma porta vira a entrada de outra.",
      realWorldConnection: "Os sensores inteligentes costumam combinar regras assim: movimento AND escuridão, OR um controle manual.",
      badge: { id: "circuit-builder", name: "Construtor de circuitos", description: "Encadeou duas portas." },
    },
    8: {
      title: "Nível 8: Meio somador",
      concept: "Os computadores somam números com portas lógicas.",
      missionTitle: "Desafio do minicomputador",
      missionStory: "Monte um circuito que some dois números de um bit.",
      plainGoal: "Some dois números de um bit usando portas: encontre a soma e o vai-um.",
      behaviorDescription: "Soma dois números de um bit. A soma mostra o bit do resultado; o vai-um mostra quando um valor passa para a casa seguinte.",
      outputs: [
        { name: "S", label: "Soma", source: { gate: "g1" } },
        { name: "C", label: "Vai-um", source: { gate: "g2" } },
      ],
      truthTable: {
        inputNames: { A: "Primeiro bit", B: "Segundo bit" },
        inputOnText: "1",
        inputOffText: "0",
        outputs: [
          { name: "S", label: "Bit de soma", onText: "A soma é 1", offText: "A soma é 0" },
          { name: "C", label: "Bit de vai-um", onText: "O vai-um é 1", offText: "O vai-um é 0" },
        ],
        helperText: "Teste cada par de números de um bit e compare o bit de soma com o bit de vai-um.",
      },
      hints: ["Olhe primeiro a coluna da soma: quando A e B são diferentes?", "A soma precisa da porta que é verdadeira quando exatamente uma entrada está ligada. O vai-um precisa da porta verdadeira só quando as duas estão ligadas.", "Soma = XOR(A, B). Vai-um = AND(A, B)."],
      successExplanation: "Você montou uma versão pequena de como os computadores somam números. O XOR encontra a soma e o AND encontra o vai-um.",
      realWorldConnection: "Toda calculadora e todo chip de computador somam números binários usando meios somadores e somadores completos como este.",
      badge: { id: "half-adder-hero", name: "Herói do meio somador", description: "Montou um somador binário pequeno." },
    },
    9: {
      title: "Nível 9: Desafio do sistema de segurança",
      concept: "Traduza uma frase do mundo real para lógica booleana.",
      missionTitle: "Desafio do sistema de segurança",
      missionStory: "Projete um sistema de segurança para a escola. O alarme deve tocar se a porta estiver aberta AND o professor NÃO estiver presente.",
      plainGoal: "Monte a lógica para o alarme tocar só quando a porta estiver aberta e o professor não estiver.",
      behaviorDescription: "A saída liga quando A (porta aberta) está ligado e B (professor presente) está desligado.",
      outputs: [{ name: "Y", label: "Y (alarme)", source: { gate: "g2" } }],
      truthTable: {
        inputNames: { A: "Porta aberta?", B: "Professor presente?" },
        outputs: [{ name: "Y", label: "O alarme toca?", onText: "O alarme toca", offText: "O alarme fica em silêncio" }],
        helperText: "Teste cada combinação de porta e professor para ver quando o alarme da escola deve tocar.",
      },
      hints: ["Primeiro inverta \"professor presente\" para ler \"professor NÃO presente\".", "Depois combine \"porta aberta\" com \"professor NÃO presente\", para que as duas precisem ser verdadeiras.", "g1 deve ser NOT(B) e g2 deve ser AND(A, g1)."],
      successExplanation: "Você traduziu uma frase do mundo real para lógica booleana, a mesma habilidade usada para escrever software de segurança.",
      realWorldConnection: "Sistemas de segurança, fechaduras inteligentes e alarmes são construídos transformando frases em lógica AND/OR/NOT.",
      badge: { id: "security-system-designer", name: "Projetista de segurança", description: "Transformou uma frase em lógica booleana." },
    },
  },
}

export function getLogicLevels(language: Language): Level[] {
  if (language === "en") return LEVELS
  const localized = LOCALIZED_LEVEL_TEXT[language]
  return LEVELS.map((level) => {
    const text = localized[level.id]
    return text ? { ...level, ...text } : level
  })
}

/** 9 guided levels + level 10, the sandbox challenge (handled by SandboxChallenge). */
export const TOTAL_LEVELS = LEVELS.length + 1
export const SANDBOX_LEVEL_ID = 10
