/**
 * Week 5 — Synthetic content / misinformation investigation + AI ethics committee
 * + appeal design (framework-free, deterministic).
 *
 * Everything is fictional: invented publishers, posts, schools, and proposals. No
 * real private individuals. The verification model is based on SOURCE and CONTEXT
 * evidence — not on "spot the weird hands." The course explicitly does NOT claim it
 * can perfectly detect AI-generated content; real images can appear in false posts,
 * and AI images can be honestly labeled.
 */

/* ========================================================================== */
/* Activity 3 — Misinformation investigation                                   */
/* ========================================================================== */

export type Verdict = "trust" | "question" | "unconfirmed"

export const VERDICTS: { id: Verdict; label: string; note: string }[] = [
  { id: "trust", label: "Reasonable to trust", note: "A reliable original source and consistent context support it." },
  { id: "question", label: "Question it", note: "There are clear warning signs it is misleading or false." },
  { id: "unconfirmed", label: "Leave it unconfirmed", note: "Not enough evidence either way — don't spread it yet." },
]

/** The seven source-and-context checks students run on every post. */
export type Evidence = {
  publisher: string
  originalSourceAvailable: boolean
  dateCorrect: boolean | "unknown"
  captionMatchesContext: boolean
  hasEvidence: boolean
  independentConfirmation: boolean
  asksForEmotionFirst: boolean
}

export type Post = {
  id: string
  headline: string
  /** What the post is describing (text-only; no real image shown). */
  imageDescription: string
  claim: string
  kind: string
  evidence: Evidence
  verdict: Verdict
  explanation: string
  /** A teaching note, e.g. about the limits of visual "tells". */
  teachingNote: string
}

export const POSTS: Post[] = [
  {
    id: "post-ai-labeled",
    headline: "Art club shares an AI-made poster — and says so",
    imageDescription: "A colorful illustration of a robot painting, with a clear caption: “Illustration generated with AI by the Art Club.”",
    claim: "This poster image was made with an AI tool.",
    kind: "AI-generated illustration, honestly labeled",
    evidence: { publisher: "School Art Club (named)", originalSourceAvailable: true, dateCorrect: true, captionMatchesContext: true, hasEvidence: true, independentConfirmation: true, asksForEmotionFirst: false },
    verdict: "trust",
    explanation: "The image is openly labeled as AI-generated by a named source, and the caption matches. AI content isn't automatically bad — labeling it honestly is exactly the responsible thing to do.",
    teachingNote: "An AI-generated image can be shared responsibly when it is clearly labeled.",
  },
  {
    id: "post-edited-caption",
    headline: "“Our town flooded last night!” — with a dramatic photo",
    imageDescription: "A real photo of a flooded street, captioned as if it happened in the reader's town last night.",
    claim: "This flood photo shows our town last night.",
    kind: "Real image with a misleading caption",
    evidence: { publisher: "Anonymous account", originalSourceAvailable: true, dateCorrect: false, captionMatchesContext: false, hasEvidence: false, independentConfirmation: false, asksForEmotionFirst: true },
    verdict: "question",
    explanation: "A reverse image search shows the photo is real but from a different town three years ago. A real image can still be used in a false post when the caption changes its context.",
    teachingNote: "Real images can be reused in false posts — always check the original context and date.",
  },
  {
    id: "post-wrong-context",
    headline: "“Robots are taking over the school!”",
    imageDescription: "A photo of a robotics competition, captioned to suggest robots are replacing teachers.",
    claim: "Robots have replaced teachers at this school.",
    kind: "Real image placed in the wrong context",
    evidence: { publisher: "Fan blog", originalSourceAvailable: true, dateCorrect: true, captionMatchesContext: false, hasEvidence: false, independentConfirmation: false, asksForEmotionFirst: true },
    verdict: "question",
    explanation: "The photo really is from a robotics event, but the original was a student competition — nothing about replacing teachers. The image is genuine; the story around it is invented.",
    teachingNote: "A genuine image says nothing about a claim bolted onto it — check what the original was about.",
  },
  {
    id: "post-fake-quote",
    headline: "Principal “confirms” no homework ever again",
    imageDescription: "A text post with a quotation attributed to the school principal.",
    claim: "The principal said homework is banned forever.",
    kind: "Fabricated quote",
    evidence: { publisher: "Meme page", originalSourceAvailable: false, dateCorrect: "unknown", captionMatchesContext: false, hasEvidence: false, independentConfirmation: false, asksForEmotionFirst: true },
    verdict: "question",
    explanation: "There's no original announcement, letter, or recording — the quote can't be traced anywhere. Invented quotes are a common trick; a claim with no findable original source should be doubted.",
    teachingNote: "If a quote can't be traced to a real original record, treat it as unverified.",
  },
  {
    id: "post-false-date",
    headline: "“Science fair cancelled — today!”",
    imageDescription: "A screenshot of a notice with today's date, about a cancelled event.",
    claim: "The science fair is cancelled today.",
    kind: "False date",
    evidence: { publisher: "Reposted screenshot", originalSourceAvailable: true, dateCorrect: false, captionMatchesContext: true, hasEvidence: false, independentConfirmation: false, asksForEmotionFirst: true },
    verdict: "question",
    explanation: "The original notice was from last year's fair; someone changed the date on the repost. Comparing the claimed date with the original reveals the mismatch.",
    teachingNote: "Check the date on the original, not the date on the repost.",
  },
  {
    id: "post-no-source",
    headline: "“90% of students prefer robots to homework”",
    imageDescription: "A bold statistic in large text with no link or study named.",
    claim: "90% of students prefer robots to homework.",
    kind: "Claim with no original source",
    evidence: { publisher: "Unknown", originalSourceAvailable: false, dateCorrect: "unknown", captionMatchesContext: true, hasEvidence: false, independentConfirmation: false, asksForEmotionFirst: false },
    verdict: "unconfirmed",
    explanation: "There's no study, survey, or source behind the number. It isn't clearly false, but with no evidence at all you can't confirm it — so don't spread it.",
    teachingNote: "A confident-sounding statistic with no source is unconfirmed, not proven.",
  },
  {
    id: "post-reliable",
    headline: "District posts the official science-fair schedule",
    imageDescription: "A schedule on the school district's official website, with a clear date and contact.",
    claim: "The science fair is on the date shown on the district site.",
    kind: "Claim supported by a reliable original source",
    evidence: { publisher: "School district (official site)", originalSourceAvailable: true, dateCorrect: true, captionMatchesContext: true, hasEvidence: true, independentConfirmation: true, asksForEmotionFirst: false },
    verdict: "trust",
    explanation: "The claim comes straight from the official original source, the date checks out, and the school newsletter independently lists the same date. Source + context + confirmation all line up.",
    teachingNote: "A reliable original source that others independently confirm is the strongest evidence.",
  },
  {
    id: "post-emotional",
    headline: "“SHARE NOW or your class loses its trip!!!”",
    imageDescription: "An all-caps post with urgent language demanding shares before it's “too late.”",
    claim: "Sharing this post will save your class trip.",
    kind: "Post designed to create an emotional reaction",
    evidence: { publisher: "Anonymous chain post", originalSourceAvailable: false, dateCorrect: "unknown", captionMatchesContext: false, hasEvidence: false, independentConfirmation: false, asksForEmotionFirst: true },
    verdict: "question",
    explanation: "It pushes urgency and fear to make you share before thinking, and has no source or evidence. Posts that demand an emotional reaction before showing evidence are a strong warning sign.",
    teachingNote: "When a post rushes you to feel and share before it shows evidence, slow down and check.",
  },
]

export type EvidenceItem = { key: keyof Evidence; question: string; good: (e: Evidence) => boolean; describe: (e: Evidence) => string }

/** The seven investigation questions, each with how to read the evidence. */
export const EVIDENCE_ITEMS: EvidenceItem[] = [
  { key: "publisher", question: "Who published it?", good: (e) => /official|named|district|club/i.test(e.publisher), describe: (e) => `Published by: ${e.publisher}.` },
  { key: "originalSourceAvailable", question: "Is the original source available?", good: (e) => e.originalSourceAvailable, describe: (e) => (e.originalSourceAvailable ? "An original source can be found." : "No original source can be found.") },
  { key: "dateCorrect", question: "Is the date correct?", good: (e) => e.dateCorrect === true, describe: (e) => (e.dateCorrect === true ? "The date checks out against the original." : e.dateCorrect === false ? "The date does not match the original." : "The date can't be checked.") },
  { key: "captionMatchesContext", question: "Does the caption match the original context?", good: (e) => e.captionMatchesContext, describe: (e) => (e.captionMatchesContext ? "The caption matches the original context." : "The caption changes or misstates the original context.") },
  { key: "hasEvidence", question: "Is there evidence?", good: (e) => e.hasEvidence, describe: (e) => (e.hasEvidence ? "Supporting evidence is provided." : "No supporting evidence is provided.") },
  { key: "independentConfirmation", question: "Do independent reliable sources confirm it?", good: (e) => e.independentConfirmation, describe: (e) => (e.independentConfirmation ? "Independent reliable sources confirm it." : "No independent source confirms it.") },
  { key: "asksForEmotionFirst", question: "Does it push an emotional reaction before evidence?", good: (e) => !e.asksForEmotionFirst, describe: (e) => (e.asksForEmotionFirst ? "It pushes an emotional reaction before showing evidence." : "It does not rush you emotionally.") },
]

/** Counts how many of the seven checks look healthy for a post. */
export function evidenceScore(post: Post): { good: number; total: number } {
  return { good: EVIDENCE_ITEMS.filter((it) => it.good(post.evidence)).length, total: EVIDENCE_ITEMS.length }
}

/* ========================================================================== */
/* Activity 4 — AI ethics committee                                            */
/* ========================================================================== */

export type Stakes = "low" | "high"
export type Decision = "approve" | "approve-safeguards" | "limited-pilot" | "reject" | "require-human-review"

export const DECISIONS: { id: Decision; label: string }[] = [
  { id: "approve", label: "Approve" },
  { id: "approve-safeguards", label: "Approve with safeguards" },
  { id: "limited-pilot", label: "Limited pilot" },
  { id: "require-human-review", label: "Require human review before use" },
  { id: "reject", label: "Reject" },
]

export type SafeguardId = "human-review" | "appeal" | "data-minimization" | "explanation" | "representation-check" | "opt-out" | "limited-scope"

export const SAFEGUARDS: { id: SafeguardId; label: string }[] = [
  { id: "human-review", label: "A person reviews high-stakes results" },
  { id: "appeal", label: "Users can appeal or correct a result" },
  { id: "data-minimization", label: "Collect only the data it needs" },
  { id: "explanation", label: "Show users why a decision was made" },
  { id: "representation-check", label: "Check results across different groups" },
  { id: "opt-out", label: "Let users opt out / use a non-AI option" },
  { id: "limited-scope", label: "Limit it to a low-stakes scope" },
]

export type EthicsScenario = {
  id: string
  name: string
  proposal: string
  intendedBenefit: string
  likelyMistakes: string[]
  peopleAffected: string[]
  stakes: Stakes
  /** Safeguards that are especially important for THIS scenario. */
  keySafeguards: SafeguardId[]
  /** Whether a plain non-AI process would likely be safer. */
  nonAiSaferHint: string
}

export const ETHICS_SCENARIOS: EthicsScenario[] = [
  {
    id: "eth-library",
    name: "Library-book recommender",
    proposal: "Suggest library books based on what a student borrowed before.",
    intendedBenefit: "Helps students discover books they might enjoy.",
    likelyMistakes: ["Recommending a narrow set (filter bubble)", "Missing books outside past choices"],
    peopleAffected: ["Students", "Librarians"],
    stakes: "low",
    keySafeguards: ["explanation", "opt-out", "data-minimization"],
    nonAiSaferHint: "A simple 'popular this month' shelf could work almost as well with far less data.",
  },
  {
    id: "eth-translate",
    name: "Translation assistant for announcements",
    proposal: "Auto-translate school announcements into families' languages.",
    intendedBenefit: "Helps families who speak other languages stay informed.",
    likelyMistakes: ["Mistranslating important details", "Sounding fluent but wrong"],
    peopleAffected: ["Families", "Office staff"],
    stakes: "high",
    keySafeguards: ["human-review", "explanation"],
    nonAiSaferHint: "For critical notices, a human translator should check the output before it goes out.",
  },
  {
    id: "eth-cheating",
    name: "Cheating-detection system",
    proposal: "Flag student work that an AI predicts was copied or AI-written.",
    intendedBenefit: "Aims to discourage cheating.",
    likelyMistakes: ["Falsely accusing honest students", "Bias against certain writing styles"],
    peopleAffected: ["Students (especially the wrongly flagged)", "Teachers"],
    stakes: "high",
    keySafeguards: ["human-review", "appeal", "representation-check", "explanation"],
    nonAiSaferHint: "These tools are unreliable; a teacher conversation is often fairer than an automatic flag.",
  },
  {
    id: "eth-program",
    name: "Academic-program selection tool",
    proposal: "Recommend which academic track a student should take.",
    intendedBenefit: "Tries to guide students to a good-fit program.",
    likelyMistakes: ["Limiting a student's options unfairly", "Baking in past bias"],
    peopleAffected: ["Students", "Counselors", "Families"],
    stakes: "high",
    keySafeguards: ["human-review", "appeal", "representation-check", "explanation", "opt-out"],
    nonAiSaferHint: "A counselor who talks with the student should make the final call, not an automatic score.",
  },
  {
    id: "eth-attention",
    name: "Student-attention monitoring",
    proposal: "Use the camera to track whether students look 'focused'.",
    intendedBenefit: "Claims to help teachers see who is engaged.",
    likelyMistakes: ["Misreading normal behavior as inattention", "Constant surveillance harms trust"],
    peopleAffected: ["All students", "Teachers"],
    stakes: "high",
    keySafeguards: ["representation-check", "opt-out"],
    nonAiSaferHint: "Watching students with a camera is invasive; a teacher's own judgment is safer and more respectful — this may be a case not to use AI at all.",
  },
  {
    id: "eth-chatbot",
    name: "Club-help chatbot",
    proposal: "A rule-based chatbot answers questions about clubs.",
    intendedBenefit: "Answers common questions quickly.",
    likelyMistakes: ["Fallback when it doesn't understand", "Giving a stale answer"],
    peopleAffected: ["Students"],
    stakes: "low",
    keySafeguards: ["explanation", "human-review"],
    nonAiSaferHint: "A simple FAQ page could do most of the job.",
  },
]

export function getEthicsScenario(id: string): EthicsScenario | undefined {
  return ETHICS_SCENARIOS.find((s) => s.id === id)
}

export type EthicsFeedback = {
  concerns: string[]
  strengths: string[]
  /** A soundness read: does the decision + safeguards fit the stakes? */
  soundness: "well-reasoned" | "needs-more-safeguards" | "reconsider"
}

/**
 * Evaluates an ethics decision WITHOUT declaring one choice "the" right answer. It
 * reasons about whether the chosen safeguards fit the scenario's stakes and key
 * risks, and returns structured, explanatory feedback.
 */
export function evaluateEthics(scenario: EthicsScenario, decision: Decision, safeguards: SafeguardId[]): EthicsFeedback {
  const chosen = new Set(safeguards)
  const concerns: string[] = []
  const strengths: string[] = []

  const missingKey = scenario.keySafeguards.filter((s) => !chosen.has(s))
  for (const s of scenario.keySafeguards.filter((s) => chosen.has(s))) {
    strengths.push(`You included an important safeguard: “${SAFEGUARDS.find((x) => x.id === s)!.label}”.`)
  }

  const approvesUse = decision === "approve" || decision === "approve-safeguards" || decision === "limited-pilot"

  if (scenario.stakes === "high") {
    if (decision === "approve") concerns.push("This is a high-stakes system, but plain “Approve” adds no safeguards. High-stakes AI needs human oversight and a way to appeal.")
    if (approvesUse && !chosen.has("human-review")) concerns.push("A high-stakes decision should have a person review results before they take effect.")
    if (approvesUse && !chosen.has("appeal")) concerns.push("People affected by a high-stakes decision need a way to appeal or correct it.")
  }

  if (approvesUse) {
    for (const s of missingKey) concerns.push(`Consider adding: “${SAFEGUARDS.find((x) => x.id === s)!.label}”, which matters for this scenario.`)
  }

  if (decision === "reject" && scenario.stakes === "low") {
    concerns.push("Rejecting outright may be stricter than needed here — safeguards might make a low-stakes tool acceptable. Explain your reasoning.")
  }

  if (decision === "reject" && scenario.id === "eth-attention") {
    strengths.push("Rejecting constant camera monitoring is a defensible call — sometimes the responsible choice is not to use AI.")
  }
  if (decision === "require-human-review" && scenario.stakes === "high") {
    strengths.push("Requiring human review before use fits a high-stakes system.")
  }

  let soundness: EthicsFeedback["soundness"] = "well-reasoned"
  if (concerns.some((c) => /needs|should|need a way/i.test(c)) && scenario.stakes === "high" && approvesUse && (!chosen.has("human-review") || !chosen.has("appeal"))) {
    soundness = "reconsider"
  } else if (approvesUse && missingKey.length > 1) {
    soundness = "needs-more-safeguards"
  }
  if (concerns.length === 0) strengths.push("Your decision and safeguards fit the stakes of this scenario.")

  return { concerns, strengths, soundness }
}

/* ========================================================================== */
/* Appeal & correction design                                                  */
/* ========================================================================== */

export type AppealField = { id: string; prompt: string; hint: string }

export const APPEAL_FIELDS: AppealField[] = [
  { id: "disclosure", prompt: "How does a user learn that AI influenced the decision?", hint: "e.g., a note shown with the result." },
  { id: "requestExplanation", prompt: "How does the user request an explanation?", hint: "e.g., a 'Why this?' button or a form." },
  { id: "reviewer", prompt: "Who reviews the appeal?", hint: "e.g., a teacher or a named staff member — a person, not the AI." },
  { id: "correctData", prompt: "How is incorrect data corrected?", hint: "e.g., the user can edit or flag wrong info." },
  { id: "documentation", prompt: "How is the final decision documented?", hint: "e.g., a short record of what was decided and why." },
  { id: "override", prompt: "When can the AI result be overridden?", hint: "e.g., the human reviewer can always override it." },
]

/** An appeal design is complete when every required part has a real answer. */
export function appealComplete(answers: Record<string, string>): { complete: boolean; missing: string[] } {
  const missing = APPEAL_FIELDS.filter((f) => (answers[f.id] ?? "").trim().length < 3).map((f) => f.id)
  return { complete: missing.length === 0, missing }
}
