import {
  type BuildablePieceKind,
  type FixedCell,
  type Inventory,
  type MarbleLevel,
  type PlacedPiece,
} from "@/components/ui/marble-run-types"

function piece(row: number, col: number, kind: BuildablePieceKind, orientation = 0): PlacedPiece {
  return { row, col, kind, orientation }
}

function wall(row: number, col: number): FixedCell {
  return { row, col, kind: "wall" }
}

function blocker(row: number, col: number): FixedCell {
  return lockedPiece(row, col, "blocker")
}

function hazard(row: number, col: number): FixedCell {
  return { row, col, kind: "hazard" }
}

function wrong(row: number, col: number): FixedCell {
  return { row, col, kind: "wrong" }
}

function lockedPiece(row: number, col: number, kind: BuildablePieceKind, orientation = 0): FixedCell {
  return {
    row,
    col,
    kind: "piece",
    locked: true,
    piece: { kind, orientation },
  }
}

function inventory(values: Inventory): Inventory {
  return {
    ramp: values.ramp ?? 0,
    pipe: values.pipe ?? 0,
    blocker: values.blocker ?? 0,
    bounce: values.bounce ?? 0,
  }
}

export const MARBLE_RUN_LEVELS: MarbleLevel[] = [
  {
    id: 1,
    name: "First Turn",
    objective: "Place one ramp so the falling marble rolls across and drops into the cup.",
    start: { row: 0, col: 2 },
    goal: { row: 6, col: 3 },
    fixed: [],
    inventory: inventory({ ramp: 1 }),
    knownSolution: [piece(3, 2, "ramp", 0)],
    bestKnown: 1,
  },
  {
    id: 2,
    name: "Four-Step Chain",
    objective: "Thread the marble through the blocker staircase with four ramps, then turn it back into the cup.",
    start: { row: 0, col: 1 },
    goal: { row: 7, col: 3 },
    fixed: [
      blocker(0, 2),
      blocker(0, 3),
      blocker(0, 4),
      blocker(0, 5),
      blocker(0, 6),
      blocker(0, 7),
      blocker(0, 8),
      blocker(1, 2),
      blocker(1, 3),
      blocker(1, 4),
      blocker(1, 5),
      blocker(1, 6),
      blocker(1, 7),
      blocker(1, 8),
      blocker(2, 3),
      blocker(2, 4),
      blocker(2, 5),
      blocker(2, 6),
      blocker(2, 7),
      blocker(2, 8),
      blocker(3, 4),
      blocker(3, 5),
      blocker(3, 6),
      blocker(3, 7),
      blocker(3, 8),
      blocker(4, 5),
      blocker(4, 6),
      blocker(4, 7),
      blocker(4, 8),
      blocker(5, 0),
      wall(5, 1),
      wall(5, 2),
      blocker(5, 3),
      blocker(5, 6),
      blocker(5, 7),
      blocker(5, 8),
      blocker(6, 0),
      wall(6, 1),
      wall(6, 2),
      blocker(6, 5),
      blocker(6, 6),
      blocker(6, 7),
      blocker(6, 8),
      blocker(7, 0),
      blocker(7, 1),
      blocker(7, 2),
      blocker(7, 5),
      blocker(7, 6),
      blocker(7, 7),
      blocker(7, 8),
    ],
    inventory: inventory({ ramp: 4 }),
    knownSolution: [
      piece(2, 1, "ramp", 0),
      piece(3, 2, "ramp", 0),
      piece(4, 3, "ramp", 0),
      piece(6, 4, "ramp", 1),
    ],
    bestKnown: 4,
  },
  {
    id: 3,
    name: "Drop Lane",
    objective: "Let the marble fall through the open chute, then use one ramp to turn left before the wall.",
    start: { row: 0, col: 6 },
    goal: { row: 7, col: 5 },
    fixed: [
      blocker(0, 7),
      blocker(0, 8),
      blocker(1, 7),
      blocker(1, 8),
      blocker(2, 2),
      blocker(2, 3),
      blocker(2, 4),
      blocker(2, 5),
      blocker(2, 7),
      blocker(2, 8),
      blocker(3, 0),
      blocker(3, 2),
      blocker(4, 0),
      blocker(5, 0),
      blocker(5, 1),
      blocker(5, 2),
      blocker(5, 3),
      wall(5, 6),
      blocker(6, 4),
      wall(6, 6),
      blocker(7, 4),
      blocker(7, 6),
    ],
    inventory: inventory({ ramp: 1 }),
    knownSolution: [piece(4, 6, "ramp", 1)],
    bestKnown: 1,
  },
  {
    id: 4,
    name: "Blocked Shaft",
    objective: "Use pipes to cross the upper channel, then turn back into the cup lane below the blocker wall.",
    start: { row: 0, col: 2 },
    goal: { row: 7, col: 3 },
    fixed: [
      blocker(0, 0),
      blocker(0, 1),
      blocker(1, 0),
      blocker(1, 1),
      blocker(2, 0),
      blocker(2, 1),
      blocker(2, 2),
      blocker(2, 3),
      blocker(2, 4),
      blocker(3, 0),
      blocker(3, 1),
      blocker(3, 2),
      blocker(3, 3),
      blocker(3, 4),
      blocker(3, 5),
      blocker(4, 0),
      blocker(4, 1),
      wall(4, 2),
      blocker(4, 7),
      blocker(5, 0),
      blocker(5, 1),
      wall(5, 2),
      blocker(5, 4),
      blocker(5, 5),
      blocker(5, 6),
      blocker(6, 0),
      blocker(6, 1),
      wall(6, 2),
      blocker(6, 8),
      blocker(7, 0),
      blocker(7, 1),
      blocker(7, 2),
      blocker(7, 4),
      blocker(7, 5),
      blocker(7, 6),
      blocker(7, 7),
    ],
    inventory: inventory({ ramp: 3, pipe: 10 }),
    knownSolution: [
      piece(1, 2, "pipe", 2),
      piece(1, 3, "pipe", 1),
      piece(1, 4, "pipe", 1),
      piece(2, 5, "pipe", 2),
      piece(4, 6, "pipe", 3),
      piece(4, 5, "pipe", 1),
      piece(4, 4, "pipe", 1),
    ],
    bestKnown: 7,
  },
  {
    id: 5,
    name: "Two-Way Maze",
    objective: "Route the marble around the blocker field. There are enough ramps and pipes to solve it from either side.",
    start: { row: 0, col: 3 },
    goal: { row: 7, col: 6 },
    fixed: [
      blocker(0, 4),
      blocker(1, 2),
      blocker(1, 4),
      blocker(1, 5),
      blocker(1, 6),
      blocker(1, 7),
      blocker(1, 8),
      blocker(2, 1),
      blocker(2, 5),
      blocker(2, 7),
      blocker(2, 8),
      blocker(3, 0),
      blocker(3, 3),
      blocker(3, 8),
      blocker(4, 0),
      blocker(4, 2),
      wall(4, 3),
      wall(4, 4),
      blocker(4, 5),
      blocker(4, 6),
      blocker(4, 8),
      blocker(5, 0),
      wall(5, 4),
      blocker(5, 8),
      blocker(6, 0),
      blocker(6, 1),
      blocker(6, 7),
      blocker(6, 8),
      blocker(7, 2),
      blocker(7, 3),
      blocker(7, 4),
      blocker(7, 5),
    ],
    inventory: inventory({ ramp: 7, pipe: 7 }),
    knownSolution: [
      piece(2, 3, "pipe", 2),
      piece(2, 4, "pipe", 5),
      piece(3, 4, "pipe", 2),
      piece(3, 5, "pipe", 1),
      piece(3, 6, "pipe", 1),
      piece(3, 7, "pipe", 5),
      piece(5, 7, "pipe", 3),
    ],
    bestKnown: 7,
  },
  {
    id: 6,
    name: "Twin Passages",
    objective: "Use ramps and pipes to guide the marble around either side of the blocker field.",
    start: { row: 0, col: 1 },
    goal: { row: 7, col: 5 },
    fixed: [
      blocker(0, 0),
      blocker(0, 2),
      blocker(0, 3),
      blocker(0, 4),
      blocker(0, 5),
      blocker(0, 6),
      blocker(0, 7),
      blocker(1, 7),
      blocker(1, 8),
      blocker(2, 1),
      blocker(2, 2),
      blocker(2, 3),
      blocker(2, 4),
      blocker(2, 8),
      blocker(3, 6),
      blocker(3, 8),
      blocker(4, 5),
      blocker(4, 8),
      wall(5, 1),
      blocker(5, 2),
      blocker(5, 8),
      wall(6, 1),
      blocker(6, 2),
      wall(6, 3),
      blocker(6, 4),
      blocker(6, 7),
      blocker(6, 8),
      blocker(7, 0),
      blocker(7, 1),
      blocker(7, 2),
      blocker(7, 3),
      blocker(7, 4),
      blocker(7, 6),
      blocker(7, 7),
      blocker(7, 8),
    ],
    inventory: inventory({ ramp: 7, pipe: 7 }),
    knownSolution: [
      piece(1, 1, "ramp", 1),
      piece(4, 0, "ramp", 0),
      piece(4, 1, "pipe", 1),
      piece(4, 2, "pipe", 1),
      piece(4, 3, "pipe", 1),
      piece(4, 4, "pipe", 5),
      piece(5, 4, "ramp", 0),
    ],
    bestKnown: 7,
  },
  {
    id: 7,
    name: "Exact Count",
    objective: "Ramps are limited, so use pipes carefully to make either edge route count.",
    start: { row: 0, col: 7 },
    goal: { row: 7, col: 4 },
    fixed: [
      blocker(0, 0),
      blocker(0, 1),
      blocker(0, 4),
      blocker(0, 5),
      blocker(1, 0),
      blocker(2, 7),
      blocker(3, 1),
      blocker(3, 2),
      blocker(3, 3),
      blocker(3, 4),
      blocker(3, 5),
      blocker(3, 6),
      blocker(3, 7),
      wall(4, 7),
      blocker(5, 0),
      blocker(5, 1),
      blocker(6, 0),
      blocker(6, 1),
      wall(6, 5),
      wall(6, 6),
      blocker(6, 7),
      blocker(6, 8),
      blocker(7, 0),
      blocker(7, 1),
      blocker(7, 2),
      blocker(7, 3),
      blocker(7, 5),
      blocker(7, 6),
      blocker(7, 7),
      blocker(7, 8),
    ],
    inventory: inventory({ ramp: 3, pipe: 10 }),
    knownSolution: [
      piece(1, 7, "ramp", 0),
      piece(5, 8, "ramp", 1),
      piece(5, 7, "pipe", 1),
      piece(5, 6, "pipe", 1),
      piece(5, 5, "pipe", 1),
    ],
    bestKnown: 5,
  },
  {
    id: 8,
    name: "Hazard Line",
    objective: "Carry the marble over the hazard cells, then let it drop in a safe column.",
    start: { row: 0, col: 2 },
    goal: { row: 7, col: 5 },
    fixed: [
      blocker(0, 0),
      blocker(0, 1),
      blocker(0, 3),
      blocker(0, 4),
      blocker(0, 5),
      blocker(0, 6),
      blocker(0, 7),
      blocker(0, 8),
      blocker(1, 0),
      blocker(1, 1),
      blocker(1, 8),
      blocker(2, 0),
      blocker(2, 2),
      blocker(2, 4),
      blocker(2, 5),
      blocker(2, 6),
      blocker(2, 8),
      blocker(3, 0),
      blocker(3, 5),
      blocker(3, 6),
      blocker(3, 8),
      blocker(4, 0),
      hazard(4, 3),
      blocker(4, 6),
      blocker(4, 8),
      blocker(5, 0),
      blocker(5, 1),
      hazard(5, 4),
      blocker(5, 8),
      blocker(6, 0),
      blocker(6, 1),
      wall(6, 2),
      blocker(6, 4),
      blocker(6, 7),
      blocker(6, 8),
      blocker(7, 0),
      blocker(7, 1),
      blocker(7, 2),
      wrong(7, 3),
      blocker(7, 4),
      blocker(7, 6),
      blocker(7, 7),
      blocker(7, 8),
    ],
    inventory: inventory({ ramp: 3, pipe: 2 }),
    knownSolution: [
      piece(1, 2, "ramp", 0),
      piece(3, 3, "pipe", 2),
      piece(4, 4, "ramp", 0),
    ],
    bestKnown: 3,
  },
  {
    id: 9,
    name: "Spring Launch",
    objective: "Use the bounce pad to launch sideways into the pipe.",
    start: { row: 0, col: 4 },
    goal: { row: 7, col: 6 },
    fixed: [
      blocker(0, 0),
      blocker(0, 1),
      blocker(0, 2),
      blocker(0, 7),
      blocker(0, 8),
      blocker(1, 0),
      blocker(1, 1),
      blocker(1, 8),
      blocker(2, 0),
      blocker(2, 4),
      blocker(2, 6),
      blocker(2, 8),
      blocker(3, 1),
      blocker(3, 3),
      blocker(3, 4),
      blocker(3, 6),
      blocker(3, 7),
      blocker(4, 1),
      blocker(4, 3),
      blocker(4, 6),
      blocker(4, 7),
      blocker(5, 1),
      wall(5, 4),
      blocker(5, 6),
      blocker(6, 0),
      blocker(6, 1),
      blocker(6, 2),
      hazard(6, 5),
      blocker(6, 8),
      blocker(7, 0),
      blocker(7, 1),
      blocker(7, 2),
      blocker(7, 3),
      blocker(7, 7),
      blocker(7, 8),
    ],
    inventory: inventory({ ramp: 4, pipe: 1, bounce: 1 }),
    knownSolution: [
      piece(1, 4, "bounce", 2),
      piece(2, 3, "ramp", 1),
      piece(5, 2, "ramp", 0),
      piece(6, 3, "ramp", 0),
      piece(7, 4, "ramp", 0),
      piece(7, 5, "pipe", 1),
    ],
    bestKnown: 6,
  },
  {
    id: 10,
    name: "Left Launch",
    objective: "Launch left, bridge the gap with pipes, then turn downward before the hazard.",
    start: { row: 0, col: 7 },
    goal: { row: 7, col: 3 },
    fixed: [
      blocker(0, 0),
      blocker(0, 2),
      blocker(0, 3),
      blocker(0, 4),
      blocker(0, 5),
      blocker(0, 6),
      blocker(0, 8),
      blocker(1, 1),
      blocker(1, 6),
      blocker(1, 8),
      blocker(2, 0),
      blocker(2, 3),
      blocker(2, 5),
      blocker(3, 2),
      blocker(3, 3),
      blocker(3, 4),
      wall(3, 7),
      wall(4, 7),
      blocker(5, 2),
      blocker(6, 1),
      blocker(6, 2),
      hazard(6, 4),
      blocker(6, 8),
      blocker(7, 0),
      blocker(7, 1),
      blocker(7, 2),
      wrong(7, 5),
      blocker(7, 6),
      blocker(7, 7),
      blocker(7, 8),
    ],
    inventory: inventory({ ramp: 3, pipe: 7 }),
    knownSolution: [
      piece(2, 7, "ramp", 1),
      piece(5, 6, "pipe", 3),
      piece(5, 5, "pipe", 1),
      piece(5, 4, "pipe", 1),
    ],
    bestKnown: 4,
  },
  {
    id: 11,
    name: "Pipe Elbow",
    objective: "Send the marble through a vertical pipe and turn it into a horizontal run.",
    start: { row: 0, col: 0 },
    goal: { row: 7, col: 4 },
    fixed: [
      blocker(0, 2),
      blocker(0, 3),
      blocker(0, 4),
      blocker(0, 5),
      blocker(0, 8),
      blocker(1, 3),
      blocker(1, 4),
      blocker(2, 0),
      blocker(2, 1),
      blocker(2, 4),
      blocker(2, 5),
      blocker(2, 7),
      blocker(2, 8),
      blocker(3, 1),
      blocker(3, 2),
      blocker(3, 8),
      wall(4, 0),
      blocker(4, 2),
      blocker(4, 4),
      blocker(4, 5),
      blocker(4, 6),
      blocker(4, 8),
      wall(5, 0),
      blocker(5, 4),
      blocker(5, 8),
      blocker(6, 0),
      hazard(6, 2),
      blocker(6, 3),
      blocker(6, 7),
      blocker(6, 8),
      blocker(7, 0),
      blocker(7, 5),
      blocker(7, 6),
      blocker(7, 7),
      blocker(7, 8),
    ],
    inventory: inventory({ ramp: 5, pipe: 4 }),
    knownSolution: [
      piece(1, 0, "ramp", 0),
      piece(1, 1, "pipe", 1),
      piece(1, 2, "ramp", 0),
      piece(2, 2, "ramp", 0),
      piece(5, 3, "ramp", 1),
      piece(5, 2, "pipe", 1),
      piece(7, 1, "ramp", 0),
      piece(7, 2, "pipe", 1),
      piece(7, 3, "pipe", 1),
    ],
    bestKnown: 9,
  },
  {
    id: 12,
    name: "False Cups",
    objective: "Avoid the wrong catch area. Turn left early and pipe the marble over to the real cup.",
    start: { row: 0, col: 5 },
    goal: { row: 7, col: 1 },
    fixed: [
      blocker(0, 0),
      blocker(0, 1),
      blocker(0, 2),
      blocker(0, 7),
      blocker(0, 8),
      blocker(1, 0),
      blocker(1, 1),
      blocker(1, 2),
      blocker(1, 7),
      blocker(1, 8),
      blocker(2, 0),
      blocker(2, 1),
      blocker(2, 5),
      blocker(2, 7),
      blocker(2, 8),
      blocker(3, 3),
      blocker(3, 4),
      blocker(3, 7),
      blocker(3, 8),
      blocker(4, 0),
      blocker(4, 2),
      blocker(4, 3),
      blocker(4, 6),
      blocker(4, 7),
      blocker(4, 8),
      blocker(5, 0),
      blocker(5, 2),
      blocker(5, 3),
      wall(5, 5),
      blocker(5, 6),
      blocker(5, 7),
      blocker(5, 8),
      blocker(6, 0),
      blocker(6, 2),
      blocker(6, 3),
      wall(6, 5),
      blocker(6, 6),
      blocker(6, 7),
      blocker(6, 8),
      blocker(7, 0),
      blocker(7, 2),
      blocker(7, 3),
      wrong(7, 4),
      wrong(7, 5),
      blocker(7, 6),
      blocker(7, 7),
      blocker(7, 8),
    ],
    inventory: inventory({ ramp: 3, pipe: 1 }),
    knownSolution: [
      piece(1, 5, "ramp", 1),
      piece(2, 4, "ramp", 1),
      piece(2, 3, "pipe", 1),
      piece(3, 2, "ramp", 1),
    ],
    bestKnown: 4,
  },
  {
    id: 13,
    name: "High Bridge",
    objective: "Use the bounce pad and pipes to cross above a dangerous lower channel.",
    start: { row: 0, col: 3 },
    goal: { row: 7, col: 8 },
    fixed: [
      blocker(0, 0),
      blocker(0, 1),
      blocker(0, 2),
      blocker(0, 8),
      blocker(1, 0),
      blocker(1, 1),
      blocker(1, 8),
      blocker(2, 0),
      blocker(2, 3),
      blocker(2, 5),
      blocker(2, 6),
      blocker(2, 8),
      blocker(3, 2),
      blocker(3, 3),
      blocker(3, 6),
      blocker(3, 8),
      blocker(4, 0),
      blocker(4, 2),
      blocker(4, 3),
      hazard(4, 4),
      blocker(4, 6),
      blocker(4, 8),
      blocker(5, 0),
      wall(5, 3),
      blocker(5, 4),
      hazard(5, 5),
      blocker(5, 8),
      blocker(6, 0),
      blocker(6, 1),
      blocker(6, 5),
      hazard(6, 6),
      blocker(7, 0),
      blocker(7, 1),
      blocker(7, 2),
    ],
    inventory: inventory({ ramp: 1, pipe: 4, bounce: 1 }),
    knownSolution: [
      piece(1, 3, "bounce", 0),
      piece(1, 4, "pipe", 1),
      piece(1, 5, "pipe", 1),
      piece(1, 6, "pipe", 1),
      piece(1, 7, "pipe", 5),
      piece(6, 7, "ramp", 0),
    ],
    bestKnown: 6,
  },
  {
    id: 14,
    name: "Locked Chute",
    objective: "Use the fixed pipe as part of the track, then add the missing turn and pipe.",
    start: { row: 0, col: 4 },
    goal: { row: 7, col: 2 },
    fixed: [
      blocker(0, 0),
      blocker(0, 1),
      blocker(0, 2),
      blocker(0, 3),
      blocker(0, 5),
      blocker(1, 0),
      blocker(1, 1),
      blocker(1, 3),
      blocker(1, 5),
      blocker(2, 3),
      lockedPiece(2, 4, "pipe", 0),
      blocker(2, 5),
      blocker(2, 6),
      blocker(2, 7),
      blocker(3, 0),
      blocker(3, 7),
      blocker(3, 8),
      blocker(4, 0),
      blocker(4, 1),
      blocker(4, 4),
      blocker(4, 8),
      blocker(5, 0),
      blocker(5, 1),
      wall(5, 4),
      blocker(5, 5),
      blocker(5, 8),
      blocker(6, 0),
      blocker(6, 1),
      hazard(6, 3),
      wall(6, 4),
      blocker(6, 5),
      blocker(6, 6),
      blocker(6, 8),
      blocker(7, 0),
      blocker(7, 1),
      blocker(7, 8),
    ],
    inventory: inventory({ ramp: 1, pipe: 1 }),
    knownSolution: [piece(3, 4, "ramp", 1), piece(3, 3, "pipe", 1)],
    bestKnown: 2,
  },
  {
    id: 15,
    name: "Final Course",
    objective: "Thread ramps and pipes around the wall, stay above the hazards, and drop into the cup.",
    start: { row: 0, col: 1 },
    goal: { row: 7, col: 6 },
    fixed: [
      blocker(0, 0),
      blocker(0, 4),
      blocker(0, 5),
      blocker(0, 6),
      blocker(0, 7),
      blocker(0, 8),
      blocker(1, 0),
      blocker(1, 5),
      blocker(1, 6),
      blocker(1, 7),
      blocker(1, 8),
      blocker(2, 0),
      blocker(2, 2),
      blocker(2, 3),
      blocker(2, 6),
      blocker(2, 7),
      blocker(2, 8),
      blocker(3, 0),
      blocker(3, 3),
      blocker(3, 7),
      blocker(3, 8),
      blocker(4, 0),
      hazard(4, 3),
      blocker(4, 8),
      blocker(5, 0),
      wall(5, 1),
      hazard(5, 4),
      blocker(5, 8),
      blocker(6, 0),
      blocker(6, 1),
      hazard(6, 5),
      blocker(7, 0),
      blocker(7, 1),
      blocker(7, 2),
      wrong(7, 3),
    ],
    inventory: inventory({ ramp: 3, pipe: 3 }),
    knownSolution: [
      piece(4, 1, "ramp", 0),
      piece(6, 2, "ramp", 0),
      piece(6, 3, "pipe", 1),
      piece(7, 4, "ramp", 0),
      piece(7, 5, "pipe", 1),
    ],
    bestKnown: 5,
  },
]
